// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

#ifndef PROTOBUF_book_2eproto__INCLUDED
#define PROTOBUF_book_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace book_mgr {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_book_2eproto();
void protobuf_AssignDesc_book_2eproto();
void protobuf_ShutdownFile_book_2eproto();

class BaseResp;
class Book;
class CreateBookReq;
class CreateBookResp;
class GetBookReq;
class GetBookResp;
class UpdateBookReq;
class UpdateBookResp;
class DeleteBookReq;
class DeleteBookResp;
class BookReq;
class BookResp;

enum OpType {
  OP_UNKNOWN = 0,
  OP_CREATE = 1,
  OP_READ = 2,
  OP_UPDATE = 3,
  OP_DELETE = 4
};
bool OpType_IsValid(int value);
const OpType OpType_MIN = OP_UNKNOWN;
const OpType OpType_MAX = OP_DELETE;
const int OpType_ARRAYSIZE = OpType_MAX + 1;

const ::google::protobuf::EnumDescriptor* OpType_descriptor();
inline const ::std::string& OpType_Name(OpType value) {
  return ::google::protobuf::internal::NameOfEnum(
    OpType_descriptor(), value);
}
inline bool OpType_Parse(
    const ::std::string& name, OpType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OpType>(
    OpType_descriptor(), name, value);
}
// ===================================================================

class BaseResp : public ::google::protobuf::Message {
 public:
  BaseResp();
  virtual ~BaseResp();

  BaseResp(const BaseResp& from);

  inline BaseResp& operator=(const BaseResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseResp& default_instance();

  void Swap(BaseResp* other);

  // implements Message ----------------------------------------------

  BaseResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseResp& from);
  void MergeFrom(const BaseResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ret_code = 1;
  inline bool has_ret_code() const;
  inline void clear_ret_code();
  static const int kRetCodeFieldNumber = 1;
  inline ::google::protobuf::int32 ret_code() const;
  inline void set_ret_code(::google::protobuf::int32 value);

  // optional string ret_msg = 2;
  inline bool has_ret_msg() const;
  inline void clear_ret_msg();
  static const int kRetMsgFieldNumber = 2;
  inline const ::std::string& ret_msg() const;
  inline void set_ret_msg(const ::std::string& value);
  inline void set_ret_msg(const char* value);
  inline void set_ret_msg(const char* value, size_t size);
  inline ::std::string* mutable_ret_msg();
  inline ::std::string* release_ret_msg();
  inline void set_allocated_ret_msg(::std::string* ret_msg);

  // @@protoc_insertion_point(class_scope:book_mgr.BaseResp)
 private:
  inline void set_has_ret_code();
  inline void clear_has_ret_code();
  inline void set_has_ret_msg();
  inline void clear_has_ret_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* ret_msg_;
  ::google::protobuf::int32 ret_code_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static BaseResp* default_instance_;
};
// -------------------------------------------------------------------

class Book : public ::google::protobuf::Message {
 public:
  Book();
  virtual ~Book();

  Book(const Book& from);

  inline Book& operator=(const Book& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Book& default_instance();

  void Swap(Book* other);

  // implements Message ----------------------------------------------

  Book* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Book& from);
  void MergeFrom(const Book& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string book_id = 1;
  inline bool has_book_id() const;
  inline void clear_book_id();
  static const int kBookIdFieldNumber = 1;
  inline const ::std::string& book_id() const;
  inline void set_book_id(const ::std::string& value);
  inline void set_book_id(const char* value);
  inline void set_book_id(const char* value, size_t size);
  inline ::std::string* mutable_book_id();
  inline ::std::string* release_book_id();
  inline void set_allocated_book_id(::std::string* book_id);

  // optional string title = 2;
  inline bool has_title() const;
  inline void clear_title();
  static const int kTitleFieldNumber = 2;
  inline const ::std::string& title() const;
  inline void set_title(const ::std::string& value);
  inline void set_title(const char* value);
  inline void set_title(const char* value, size_t size);
  inline ::std::string* mutable_title();
  inline ::std::string* release_title();
  inline void set_allocated_title(::std::string* title);

  // optional string author = 3;
  inline bool has_author() const;
  inline void clear_author();
  static const int kAuthorFieldNumber = 3;
  inline const ::std::string& author() const;
  inline void set_author(const ::std::string& value);
  inline void set_author(const char* value);
  inline void set_author(const char* value, size_t size);
  inline ::std::string* mutable_author();
  inline ::std::string* release_author();
  inline void set_allocated_author(::std::string* author);

  // optional int32 price = 4;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 4;
  inline ::google::protobuf::int32 price() const;
  inline void set_price(::google::protobuf::int32 value);

  // optional int32 stock = 5;
  inline bool has_stock() const;
  inline void clear_stock();
  static const int kStockFieldNumber = 5;
  inline ::google::protobuf::int32 stock() const;
  inline void set_stock(::google::protobuf::int32 value);

  // optional string category = 6;
  inline bool has_category() const;
  inline void clear_category();
  static const int kCategoryFieldNumber = 6;
  inline const ::std::string& category() const;
  inline void set_category(const ::std::string& value);
  inline void set_category(const char* value);
  inline void set_category(const char* value, size_t size);
  inline ::std::string* mutable_category();
  inline ::std::string* release_category();
  inline void set_allocated_category(::std::string* category);

  // @@protoc_insertion_point(class_scope:book_mgr.Book)
 private:
  inline void set_has_book_id();
  inline void clear_has_book_id();
  inline void set_has_title();
  inline void clear_has_title();
  inline void set_has_author();
  inline void clear_has_author();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_stock();
  inline void clear_has_stock();
  inline void set_has_category();
  inline void clear_has_category();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* book_id_;
  ::std::string* title_;
  ::std::string* author_;
  ::google::protobuf::int32 price_;
  ::google::protobuf::int32 stock_;
  ::std::string* category_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static Book* default_instance_;
};
// -------------------------------------------------------------------

class CreateBookReq : public ::google::protobuf::Message {
 public:
  CreateBookReq();
  virtual ~CreateBookReq();

  CreateBookReq(const CreateBookReq& from);

  inline CreateBookReq& operator=(const CreateBookReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateBookReq& default_instance();

  void Swap(CreateBookReq* other);

  // implements Message ----------------------------------------------

  CreateBookReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateBookReq& from);
  void MergeFrom(const CreateBookReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.Book book = 1;
  inline bool has_book() const;
  inline void clear_book();
  static const int kBookFieldNumber = 1;
  inline const ::book_mgr::Book& book() const;
  inline ::book_mgr::Book* mutable_book();
  inline ::book_mgr::Book* release_book();
  inline void set_allocated_book(::book_mgr::Book* book);

  // @@protoc_insertion_point(class_scope:book_mgr.CreateBookReq)
 private:
  inline void set_has_book();
  inline void clear_has_book();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::Book* book_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static CreateBookReq* default_instance_;
};
// -------------------------------------------------------------------

class CreateBookResp : public ::google::protobuf::Message {
 public:
  CreateBookResp();
  virtual ~CreateBookResp();

  CreateBookResp(const CreateBookResp& from);

  inline CreateBookResp& operator=(const CreateBookResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateBookResp& default_instance();

  void Swap(CreateBookResp* other);

  // implements Message ----------------------------------------------

  CreateBookResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateBookResp& from);
  void MergeFrom(const CreateBookResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::book_mgr::BaseResp& base() const;
  inline ::book_mgr::BaseResp* mutable_base();
  inline ::book_mgr::BaseResp* release_base();
  inline void set_allocated_base(::book_mgr::BaseResp* base);

  // optional string book_id = 2;
  inline bool has_book_id() const;
  inline void clear_book_id();
  static const int kBookIdFieldNumber = 2;
  inline const ::std::string& book_id() const;
  inline void set_book_id(const ::std::string& value);
  inline void set_book_id(const char* value);
  inline void set_book_id(const char* value, size_t size);
  inline ::std::string* mutable_book_id();
  inline ::std::string* release_book_id();
  inline void set_allocated_book_id(::std::string* book_id);

  // @@protoc_insertion_point(class_scope:book_mgr.CreateBookResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_book_id();
  inline void clear_has_book_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::BaseResp* base_;
  ::std::string* book_id_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static CreateBookResp* default_instance_;
};
// -------------------------------------------------------------------

class GetBookReq : public ::google::protobuf::Message {
 public:
  GetBookReq();
  virtual ~GetBookReq();

  GetBookReq(const GetBookReq& from);

  inline GetBookReq& operator=(const GetBookReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetBookReq& default_instance();

  void Swap(GetBookReq* other);

  // implements Message ----------------------------------------------

  GetBookReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetBookReq& from);
  void MergeFrom(const GetBookReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string book_id = 1;
  inline bool has_book_id() const;
  inline void clear_book_id();
  static const int kBookIdFieldNumber = 1;
  inline const ::std::string& book_id() const;
  inline void set_book_id(const ::std::string& value);
  inline void set_book_id(const char* value);
  inline void set_book_id(const char* value, size_t size);
  inline ::std::string* mutable_book_id();
  inline ::std::string* release_book_id();
  inline void set_allocated_book_id(::std::string* book_id);

  // @@protoc_insertion_point(class_scope:book_mgr.GetBookReq)
 private:
  inline void set_has_book_id();
  inline void clear_has_book_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* book_id_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static GetBookReq* default_instance_;
};
// -------------------------------------------------------------------

class GetBookResp : public ::google::protobuf::Message {
 public:
  GetBookResp();
  virtual ~GetBookResp();

  GetBookResp(const GetBookResp& from);

  inline GetBookResp& operator=(const GetBookResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetBookResp& default_instance();

  void Swap(GetBookResp* other);

  // implements Message ----------------------------------------------

  GetBookResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetBookResp& from);
  void MergeFrom(const GetBookResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::book_mgr::BaseResp& base() const;
  inline ::book_mgr::BaseResp* mutable_base();
  inline ::book_mgr::BaseResp* release_base();
  inline void set_allocated_base(::book_mgr::BaseResp* base);

  // optional .book_mgr.Book book = 2;
  inline bool has_book() const;
  inline void clear_book();
  static const int kBookFieldNumber = 2;
  inline const ::book_mgr::Book& book() const;
  inline ::book_mgr::Book* mutable_book();
  inline ::book_mgr::Book* release_book();
  inline void set_allocated_book(::book_mgr::Book* book);

  // optional bool from_cache = 3;
  inline bool has_from_cache() const;
  inline void clear_from_cache();
  static const int kFromCacheFieldNumber = 3;
  inline bool from_cache() const;
  inline void set_from_cache(bool value);

  // @@protoc_insertion_point(class_scope:book_mgr.GetBookResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_book();
  inline void clear_has_book();
  inline void set_has_from_cache();
  inline void clear_has_from_cache();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::BaseResp* base_;
  ::book_mgr::Book* book_;
  bool from_cache_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static GetBookResp* default_instance_;
};
// -------------------------------------------------------------------

class UpdateBookReq : public ::google::protobuf::Message {
 public:
  UpdateBookReq();
  virtual ~UpdateBookReq();

  UpdateBookReq(const UpdateBookReq& from);

  inline UpdateBookReq& operator=(const UpdateBookReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateBookReq& default_instance();

  void Swap(UpdateBookReq* other);

  // implements Message ----------------------------------------------

  UpdateBookReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateBookReq& from);
  void MergeFrom(const UpdateBookReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.Book book = 1;
  inline bool has_book() const;
  inline void clear_book();
  static const int kBookFieldNumber = 1;
  inline const ::book_mgr::Book& book() const;
  inline ::book_mgr::Book* mutable_book();
  inline ::book_mgr::Book* release_book();
  inline void set_allocated_book(::book_mgr::Book* book);

  // @@protoc_insertion_point(class_scope:book_mgr.UpdateBookReq)
 private:
  inline void set_has_book();
  inline void clear_has_book();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::Book* book_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static UpdateBookReq* default_instance_;
};
// -------------------------------------------------------------------

class UpdateBookResp : public ::google::protobuf::Message {
 public:
  UpdateBookResp();
  virtual ~UpdateBookResp();

  UpdateBookResp(const UpdateBookResp& from);

  inline UpdateBookResp& operator=(const UpdateBookResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateBookResp& default_instance();

  void Swap(UpdateBookResp* other);

  // implements Message ----------------------------------------------

  UpdateBookResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateBookResp& from);
  void MergeFrom(const UpdateBookResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::book_mgr::BaseResp& base() const;
  inline ::book_mgr::BaseResp* mutable_base();
  inline ::book_mgr::BaseResp* release_base();
  inline void set_allocated_base(::book_mgr::BaseResp* base);

  // @@protoc_insertion_point(class_scope:book_mgr.UpdateBookResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::BaseResp* base_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static UpdateBookResp* default_instance_;
};
// -------------------------------------------------------------------

class DeleteBookReq : public ::google::protobuf::Message {
 public:
  DeleteBookReq();
  virtual ~DeleteBookReq();

  DeleteBookReq(const DeleteBookReq& from);

  inline DeleteBookReq& operator=(const DeleteBookReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteBookReq& default_instance();

  void Swap(DeleteBookReq* other);

  // implements Message ----------------------------------------------

  DeleteBookReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteBookReq& from);
  void MergeFrom(const DeleteBookReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string book_id = 1;
  inline bool has_book_id() const;
  inline void clear_book_id();
  static const int kBookIdFieldNumber = 1;
  inline const ::std::string& book_id() const;
  inline void set_book_id(const ::std::string& value);
  inline void set_book_id(const char* value);
  inline void set_book_id(const char* value, size_t size);
  inline ::std::string* mutable_book_id();
  inline ::std::string* release_book_id();
  inline void set_allocated_book_id(::std::string* book_id);

  // @@protoc_insertion_point(class_scope:book_mgr.DeleteBookReq)
 private:
  inline void set_has_book_id();
  inline void clear_has_book_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* book_id_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static DeleteBookReq* default_instance_;
};
// -------------------------------------------------------------------

class DeleteBookResp : public ::google::protobuf::Message {
 public:
  DeleteBookResp();
  virtual ~DeleteBookResp();

  DeleteBookResp(const DeleteBookResp& from);

  inline DeleteBookResp& operator=(const DeleteBookResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteBookResp& default_instance();

  void Swap(DeleteBookResp* other);

  // implements Message ----------------------------------------------

  DeleteBookResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteBookResp& from);
  void MergeFrom(const DeleteBookResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::book_mgr::BaseResp& base() const;
  inline ::book_mgr::BaseResp* mutable_base();
  inline ::book_mgr::BaseResp* release_base();
  inline void set_allocated_base(::book_mgr::BaseResp* base);

  // @@protoc_insertion_point(class_scope:book_mgr.DeleteBookResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::BaseResp* base_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static DeleteBookResp* default_instance_;
};
// -------------------------------------------------------------------

class BookReq : public ::google::protobuf::Message {
 public:
  BookReq();
  virtual ~BookReq();

  BookReq(const BookReq& from);

  inline BookReq& operator=(const BookReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BookReq& default_instance();

  enum ReqBodyCase {
    kCreateReq = 2,
    kGetReq = 3,
    kUpdateReq = 4,
    kDeleteReq = 5,
    REQ_BODY_NOT_SET = 0,
  };

  void Swap(BookReq* other);

  // implements Message ----------------------------------------------

  BookReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BookReq& from);
  void MergeFrom(const BookReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.OpType op_type = 1;
  inline bool has_op_type() const;
  inline void clear_op_type();
  static const int kOpTypeFieldNumber = 1;
  inline ::book_mgr::OpType op_type() const;
  inline void set_op_type(::book_mgr::OpType value);

  // optional .book_mgr.CreateBookReq create_req = 2;
  inline bool has_create_req() const;
  inline void clear_create_req();
  static const int kCreateReqFieldNumber = 2;
  inline const ::book_mgr::CreateBookReq& create_req() const;
  inline ::book_mgr::CreateBookReq* mutable_create_req();
  inline ::book_mgr::CreateBookReq* release_create_req();
  inline void set_allocated_create_req(::book_mgr::CreateBookReq* create_req);

  // optional .book_mgr.GetBookReq get_req = 3;
  inline bool has_get_req() const;
  inline void clear_get_req();
  static const int kGetReqFieldNumber = 3;
  inline const ::book_mgr::GetBookReq& get_req() const;
  inline ::book_mgr::GetBookReq* mutable_get_req();
  inline ::book_mgr::GetBookReq* release_get_req();
  inline void set_allocated_get_req(::book_mgr::GetBookReq* get_req);

  // optional .book_mgr.UpdateBookReq update_req = 4;
  inline bool has_update_req() const;
  inline void clear_update_req();
  static const int kUpdateReqFieldNumber = 4;
  inline const ::book_mgr::UpdateBookReq& update_req() const;
  inline ::book_mgr::UpdateBookReq* mutable_update_req();
  inline ::book_mgr::UpdateBookReq* release_update_req();
  inline void set_allocated_update_req(::book_mgr::UpdateBookReq* update_req);

  // optional .book_mgr.DeleteBookReq delete_req = 5;
  inline bool has_delete_req() const;
  inline void clear_delete_req();
  static const int kDeleteReqFieldNumber = 5;
  inline const ::book_mgr::DeleteBookReq& delete_req() const;
  inline ::book_mgr::DeleteBookReq* mutable_delete_req();
  inline ::book_mgr::DeleteBookReq* release_delete_req();
  inline void set_allocated_delete_req(::book_mgr::DeleteBookReq* delete_req);

  inline ReqBodyCase req_body_case() const;
  // @@protoc_insertion_point(class_scope:book_mgr.BookReq)
 private:
  inline void set_has_op_type();
  inline void clear_has_op_type();
  inline void set_has_create_req();
  inline void set_has_get_req();
  inline void set_has_update_req();
  inline void set_has_delete_req();

  inline bool has_req_body();
  void clear_req_body();
  inline void clear_has_req_body();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int op_type_;
  union ReqBodyUnion {
    ::book_mgr::CreateBookReq* create_req_;
    ::book_mgr::GetBookReq* get_req_;
    ::book_mgr::UpdateBookReq* update_req_;
    ::book_mgr::DeleteBookReq* delete_req_;
  } req_body_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static BookReq* default_instance_;
};
// -------------------------------------------------------------------

class BookResp : public ::google::protobuf::Message {
 public:
  BookResp();
  virtual ~BookResp();

  BookResp(const BookResp& from);

  inline BookResp& operator=(const BookResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BookResp& default_instance();

  enum RespBodyCase {
    kCreateResp = 2,
    kGetResp = 3,
    kUpdateResp = 4,
    kDeleteResp = 5,
    RESP_BODY_NOT_SET = 0,
  };

  void Swap(BookResp* other);

  // implements Message ----------------------------------------------

  BookResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BookResp& from);
  void MergeFrom(const BookResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .book_mgr.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::book_mgr::BaseResp& base() const;
  inline ::book_mgr::BaseResp* mutable_base();
  inline ::book_mgr::BaseResp* release_base();
  inline void set_allocated_base(::book_mgr::BaseResp* base);

  // optional .book_mgr.CreateBookResp create_resp = 2;
  inline bool has_create_resp() const;
  inline void clear_create_resp();
  static const int kCreateRespFieldNumber = 2;
  inline const ::book_mgr::CreateBookResp& create_resp() const;
  inline ::book_mgr::CreateBookResp* mutable_create_resp();
  inline ::book_mgr::CreateBookResp* release_create_resp();
  inline void set_allocated_create_resp(::book_mgr::CreateBookResp* create_resp);

  // optional .book_mgr.GetBookResp get_resp = 3;
  inline bool has_get_resp() const;
  inline void clear_get_resp();
  static const int kGetRespFieldNumber = 3;
  inline const ::book_mgr::GetBookResp& get_resp() const;
  inline ::book_mgr::GetBookResp* mutable_get_resp();
  inline ::book_mgr::GetBookResp* release_get_resp();
  inline void set_allocated_get_resp(::book_mgr::GetBookResp* get_resp);

  // optional .book_mgr.UpdateBookResp update_resp = 4;
  inline bool has_update_resp() const;
  inline void clear_update_resp();
  static const int kUpdateRespFieldNumber = 4;
  inline const ::book_mgr::UpdateBookResp& update_resp() const;
  inline ::book_mgr::UpdateBookResp* mutable_update_resp();
  inline ::book_mgr::UpdateBookResp* release_update_resp();
  inline void set_allocated_update_resp(::book_mgr::UpdateBookResp* update_resp);

  // optional .book_mgr.DeleteBookResp delete_resp = 5;
  inline bool has_delete_resp() const;
  inline void clear_delete_resp();
  static const int kDeleteRespFieldNumber = 5;
  inline const ::book_mgr::DeleteBookResp& delete_resp() const;
  inline ::book_mgr::DeleteBookResp* mutable_delete_resp();
  inline ::book_mgr::DeleteBookResp* release_delete_resp();
  inline void set_allocated_delete_resp(::book_mgr::DeleteBookResp* delete_resp);

  inline RespBodyCase resp_body_case() const;
  // @@protoc_insertion_point(class_scope:book_mgr.BookResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_create_resp();
  inline void set_has_get_resp();
  inline void set_has_update_resp();
  inline void set_has_delete_resp();

  inline bool has_resp_body();
  void clear_resp_body();
  inline void clear_has_resp_body();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book_mgr::BaseResp* base_;
  union RespBodyUnion {
    ::book_mgr::CreateBookResp* create_resp_;
    ::book_mgr::GetBookResp* get_resp_;
    ::book_mgr::UpdateBookResp* update_resp_;
    ::book_mgr::DeleteBookResp* delete_resp_;
  } resp_body_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static BookResp* default_instance_;
};
// ===================================================================


// ===================================================================

// BaseResp

// optional int32 ret_code = 1;
inline bool BaseResp::has_ret_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseResp::set_has_ret_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseResp::clear_has_ret_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseResp::clear_ret_code() {
  ret_code_ = 0;
  clear_has_ret_code();
}
inline ::google::protobuf::int32 BaseResp::ret_code() const {
  // @@protoc_insertion_point(field_get:book_mgr.BaseResp.ret_code)
  return ret_code_;
}
inline void BaseResp::set_ret_code(::google::protobuf::int32 value) {
  set_has_ret_code();
  ret_code_ = value;
  // @@protoc_insertion_point(field_set:book_mgr.BaseResp.ret_code)
}

// optional string ret_msg = 2;
inline bool BaseResp::has_ret_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BaseResp::set_has_ret_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BaseResp::clear_has_ret_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BaseResp::clear_ret_msg() {
  if (ret_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_->clear();
  }
  clear_has_ret_msg();
}
inline const ::std::string& BaseResp::ret_msg() const {
  // @@protoc_insertion_point(field_get:book_mgr.BaseResp.ret_msg)
  return *ret_msg_;
}
inline void BaseResp::set_ret_msg(const ::std::string& value) {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  ret_msg_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.BaseResp.ret_msg)
}
inline void BaseResp::set_ret_msg(const char* value) {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  ret_msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.BaseResp.ret_msg)
}
inline void BaseResp::set_ret_msg(const char* value, size_t size) {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  ret_msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.BaseResp.ret_msg)
}
inline ::std::string* BaseResp::mutable_ret_msg() {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.BaseResp.ret_msg)
  return ret_msg_;
}
inline ::std::string* BaseResp::release_ret_msg() {
  clear_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ret_msg_;
    ret_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void BaseResp::set_allocated_ret_msg(::std::string* ret_msg) {
  if (ret_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ret_msg_;
  }
  if (ret_msg) {
    set_has_ret_msg();
    ret_msg_ = ret_msg;
  } else {
    clear_has_ret_msg();
    ret_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.BaseResp.ret_msg)
}

// -------------------------------------------------------------------

// Book

// optional string book_id = 1;
inline bool Book::has_book_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Book::set_has_book_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Book::clear_has_book_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Book::clear_book_id() {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_->clear();
  }
  clear_has_book_id();
}
inline const ::std::string& Book::book_id() const {
  // @@protoc_insertion_point(field_get:book_mgr.Book.book_id)
  return *book_id_;
}
inline void Book::set_book_id(const ::std::string& value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.Book.book_id)
}
inline void Book::set_book_id(const char* value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.Book.book_id)
}
inline void Book::set_book_id(const char* value, size_t size) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.Book.book_id)
}
inline ::std::string* Book::mutable_book_id() {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.Book.book_id)
  return book_id_;
}
inline ::std::string* Book::release_book_id() {
  clear_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = book_id_;
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Book::set_allocated_book_id(::std::string* book_id) {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete book_id_;
  }
  if (book_id) {
    set_has_book_id();
    book_id_ = book_id;
  } else {
    clear_has_book_id();
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.Book.book_id)
}

// optional string title = 2;
inline bool Book::has_title() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Book::set_has_title() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Book::clear_has_title() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Book::clear_title() {
  if (title_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    title_->clear();
  }
  clear_has_title();
}
inline const ::std::string& Book::title() const {
  // @@protoc_insertion_point(field_get:book_mgr.Book.title)
  return *title_;
}
inline void Book::set_title(const ::std::string& value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    title_ = new ::std::string;
  }
  title_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.Book.title)
}
inline void Book::set_title(const char* value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    title_ = new ::std::string;
  }
  title_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.Book.title)
}
inline void Book::set_title(const char* value, size_t size) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    title_ = new ::std::string;
  }
  title_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.Book.title)
}
inline ::std::string* Book::mutable_title() {
  set_has_title();
  if (title_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    title_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.Book.title)
  return title_;
}
inline ::std::string* Book::release_title() {
  clear_has_title();
  if (title_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = title_;
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Book::set_allocated_title(::std::string* title) {
  if (title_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete title_;
  }
  if (title) {
    set_has_title();
    title_ = title;
  } else {
    clear_has_title();
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.Book.title)
}

// optional string author = 3;
inline bool Book::has_author() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Book::set_has_author() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Book::clear_has_author() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Book::clear_author() {
  if (author_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    author_->clear();
  }
  clear_has_author();
}
inline const ::std::string& Book::author() const {
  // @@protoc_insertion_point(field_get:book_mgr.Book.author)
  return *author_;
}
inline void Book::set_author(const ::std::string& value) {
  set_has_author();
  if (author_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    author_ = new ::std::string;
  }
  author_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.Book.author)
}
inline void Book::set_author(const char* value) {
  set_has_author();
  if (author_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    author_ = new ::std::string;
  }
  author_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.Book.author)
}
inline void Book::set_author(const char* value, size_t size) {
  set_has_author();
  if (author_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    author_ = new ::std::string;
  }
  author_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.Book.author)
}
inline ::std::string* Book::mutable_author() {
  set_has_author();
  if (author_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    author_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.Book.author)
  return author_;
}
inline ::std::string* Book::release_author() {
  clear_has_author();
  if (author_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = author_;
    author_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Book::set_allocated_author(::std::string* author) {
  if (author_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete author_;
  }
  if (author) {
    set_has_author();
    author_ = author;
  } else {
    clear_has_author();
    author_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.Book.author)
}

// optional int32 price = 4;
inline bool Book::has_price() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Book::set_has_price() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Book::clear_has_price() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Book::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline ::google::protobuf::int32 Book::price() const {
  // @@protoc_insertion_point(field_get:book_mgr.Book.price)
  return price_;
}
inline void Book::set_price(::google::protobuf::int32 value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:book_mgr.Book.price)
}

// optional int32 stock = 5;
inline bool Book::has_stock() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Book::set_has_stock() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Book::clear_has_stock() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Book::clear_stock() {
  stock_ = 0;
  clear_has_stock();
}
inline ::google::protobuf::int32 Book::stock() const {
  // @@protoc_insertion_point(field_get:book_mgr.Book.stock)
  return stock_;
}
inline void Book::set_stock(::google::protobuf::int32 value) {
  set_has_stock();
  stock_ = value;
  // @@protoc_insertion_point(field_set:book_mgr.Book.stock)
}

// optional string category = 6;
inline bool Book::has_category() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Book::set_has_category() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Book::clear_has_category() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Book::clear_category() {
  if (category_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    category_->clear();
  }
  clear_has_category();
}
inline const ::std::string& Book::category() const {
  // @@protoc_insertion_point(field_get:book_mgr.Book.category)
  return *category_;
}
inline void Book::set_category(const ::std::string& value) {
  set_has_category();
  if (category_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    category_ = new ::std::string;
  }
  category_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.Book.category)
}
inline void Book::set_category(const char* value) {
  set_has_category();
  if (category_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    category_ = new ::std::string;
  }
  category_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.Book.category)
}
inline void Book::set_category(const char* value, size_t size) {
  set_has_category();
  if (category_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    category_ = new ::std::string;
  }
  category_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.Book.category)
}
inline ::std::string* Book::mutable_category() {
  set_has_category();
  if (category_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    category_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.Book.category)
  return category_;
}
inline ::std::string* Book::release_category() {
  clear_has_category();
  if (category_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = category_;
    category_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Book::set_allocated_category(::std::string* category) {
  if (category_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete category_;
  }
  if (category) {
    set_has_category();
    category_ = category;
  } else {
    clear_has_category();
    category_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.Book.category)
}

// -------------------------------------------------------------------

// CreateBookReq

// optional .book_mgr.Book book = 1;
inline bool CreateBookReq::has_book() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateBookReq::set_has_book() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateBookReq::clear_has_book() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateBookReq::clear_book() {
  if (book_ != NULL) book_->::book_mgr::Book::Clear();
  clear_has_book();
}
inline const ::book_mgr::Book& CreateBookReq::book() const {
  // @@protoc_insertion_point(field_get:book_mgr.CreateBookReq.book)
  return book_ != NULL ? *book_ : *default_instance_->book_;
}
inline ::book_mgr::Book* CreateBookReq::mutable_book() {
  set_has_book();
  if (book_ == NULL) book_ = new ::book_mgr::Book;
  // @@protoc_insertion_point(field_mutable:book_mgr.CreateBookReq.book)
  return book_;
}
inline ::book_mgr::Book* CreateBookReq::release_book() {
  clear_has_book();
  ::book_mgr::Book* temp = book_;
  book_ = NULL;
  return temp;
}
inline void CreateBookReq::set_allocated_book(::book_mgr::Book* book) {
  delete book_;
  book_ = book;
  if (book) {
    set_has_book();
  } else {
    clear_has_book();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.CreateBookReq.book)
}

// -------------------------------------------------------------------

// CreateBookResp

// optional .book_mgr.BaseResp base = 1;
inline bool CreateBookResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateBookResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateBookResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateBookResp::clear_base() {
  if (base_ != NULL) base_->::book_mgr::BaseResp::Clear();
  clear_has_base();
}
inline const ::book_mgr::BaseResp& CreateBookResp::base() const {
  // @@protoc_insertion_point(field_get:book_mgr.CreateBookResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::book_mgr::BaseResp* CreateBookResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::book_mgr::BaseResp;
  // @@protoc_insertion_point(field_mutable:book_mgr.CreateBookResp.base)
  return base_;
}
inline ::book_mgr::BaseResp* CreateBookResp::release_base() {
  clear_has_base();
  ::book_mgr::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void CreateBookResp::set_allocated_base(::book_mgr::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.CreateBookResp.base)
}

// optional string book_id = 2;
inline bool CreateBookResp::has_book_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateBookResp::set_has_book_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateBookResp::clear_has_book_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateBookResp::clear_book_id() {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_->clear();
  }
  clear_has_book_id();
}
inline const ::std::string& CreateBookResp::book_id() const {
  // @@protoc_insertion_point(field_get:book_mgr.CreateBookResp.book_id)
  return *book_id_;
}
inline void CreateBookResp::set_book_id(const ::std::string& value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.CreateBookResp.book_id)
}
inline void CreateBookResp::set_book_id(const char* value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.CreateBookResp.book_id)
}
inline void CreateBookResp::set_book_id(const char* value, size_t size) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.CreateBookResp.book_id)
}
inline ::std::string* CreateBookResp::mutable_book_id() {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.CreateBookResp.book_id)
  return book_id_;
}
inline ::std::string* CreateBookResp::release_book_id() {
  clear_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = book_id_;
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CreateBookResp::set_allocated_book_id(::std::string* book_id) {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete book_id_;
  }
  if (book_id) {
    set_has_book_id();
    book_id_ = book_id;
  } else {
    clear_has_book_id();
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.CreateBookResp.book_id)
}

// -------------------------------------------------------------------

// GetBookReq

// optional string book_id = 1;
inline bool GetBookReq::has_book_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetBookReq::set_has_book_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetBookReq::clear_has_book_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetBookReq::clear_book_id() {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_->clear();
  }
  clear_has_book_id();
}
inline const ::std::string& GetBookReq::book_id() const {
  // @@protoc_insertion_point(field_get:book_mgr.GetBookReq.book_id)
  return *book_id_;
}
inline void GetBookReq::set_book_id(const ::std::string& value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.GetBookReq.book_id)
}
inline void GetBookReq::set_book_id(const char* value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.GetBookReq.book_id)
}
inline void GetBookReq::set_book_id(const char* value, size_t size) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.GetBookReq.book_id)
}
inline ::std::string* GetBookReq::mutable_book_id() {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.GetBookReq.book_id)
  return book_id_;
}
inline ::std::string* GetBookReq::release_book_id() {
  clear_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = book_id_;
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GetBookReq::set_allocated_book_id(::std::string* book_id) {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete book_id_;
  }
  if (book_id) {
    set_has_book_id();
    book_id_ = book_id;
  } else {
    clear_has_book_id();
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.GetBookReq.book_id)
}

// -------------------------------------------------------------------

// GetBookResp

// optional .book_mgr.BaseResp base = 1;
inline bool GetBookResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetBookResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetBookResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetBookResp::clear_base() {
  if (base_ != NULL) base_->::book_mgr::BaseResp::Clear();
  clear_has_base();
}
inline const ::book_mgr::BaseResp& GetBookResp::base() const {
  // @@protoc_insertion_point(field_get:book_mgr.GetBookResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::book_mgr::BaseResp* GetBookResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::book_mgr::BaseResp;
  // @@protoc_insertion_point(field_mutable:book_mgr.GetBookResp.base)
  return base_;
}
inline ::book_mgr::BaseResp* GetBookResp::release_base() {
  clear_has_base();
  ::book_mgr::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void GetBookResp::set_allocated_base(::book_mgr::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.GetBookResp.base)
}

// optional .book_mgr.Book book = 2;
inline bool GetBookResp::has_book() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetBookResp::set_has_book() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetBookResp::clear_has_book() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetBookResp::clear_book() {
  if (book_ != NULL) book_->::book_mgr::Book::Clear();
  clear_has_book();
}
inline const ::book_mgr::Book& GetBookResp::book() const {
  // @@protoc_insertion_point(field_get:book_mgr.GetBookResp.book)
  return book_ != NULL ? *book_ : *default_instance_->book_;
}
inline ::book_mgr::Book* GetBookResp::mutable_book() {
  set_has_book();
  if (book_ == NULL) book_ = new ::book_mgr::Book;
  // @@protoc_insertion_point(field_mutable:book_mgr.GetBookResp.book)
  return book_;
}
inline ::book_mgr::Book* GetBookResp::release_book() {
  clear_has_book();
  ::book_mgr::Book* temp = book_;
  book_ = NULL;
  return temp;
}
inline void GetBookResp::set_allocated_book(::book_mgr::Book* book) {
  delete book_;
  book_ = book;
  if (book) {
    set_has_book();
  } else {
    clear_has_book();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.GetBookResp.book)
}

// optional bool from_cache = 3;
inline bool GetBookResp::has_from_cache() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetBookResp::set_has_from_cache() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetBookResp::clear_has_from_cache() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetBookResp::clear_from_cache() {
  from_cache_ = false;
  clear_has_from_cache();
}
inline bool GetBookResp::from_cache() const {
  // @@protoc_insertion_point(field_get:book_mgr.GetBookResp.from_cache)
  return from_cache_;
}
inline void GetBookResp::set_from_cache(bool value) {
  set_has_from_cache();
  from_cache_ = value;
  // @@protoc_insertion_point(field_set:book_mgr.GetBookResp.from_cache)
}

// -------------------------------------------------------------------

// UpdateBookReq

// optional .book_mgr.Book book = 1;
inline bool UpdateBookReq::has_book() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateBookReq::set_has_book() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateBookReq::clear_has_book() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateBookReq::clear_book() {
  if (book_ != NULL) book_->::book_mgr::Book::Clear();
  clear_has_book();
}
inline const ::book_mgr::Book& UpdateBookReq::book() const {
  // @@protoc_insertion_point(field_get:book_mgr.UpdateBookReq.book)
  return book_ != NULL ? *book_ : *default_instance_->book_;
}
inline ::book_mgr::Book* UpdateBookReq::mutable_book() {
  set_has_book();
  if (book_ == NULL) book_ = new ::book_mgr::Book;
  // @@protoc_insertion_point(field_mutable:book_mgr.UpdateBookReq.book)
  return book_;
}
inline ::book_mgr::Book* UpdateBookReq::release_book() {
  clear_has_book();
  ::book_mgr::Book* temp = book_;
  book_ = NULL;
  return temp;
}
inline void UpdateBookReq::set_allocated_book(::book_mgr::Book* book) {
  delete book_;
  book_ = book;
  if (book) {
    set_has_book();
  } else {
    clear_has_book();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.UpdateBookReq.book)
}

// -------------------------------------------------------------------

// UpdateBookResp

// optional .book_mgr.BaseResp base = 1;
inline bool UpdateBookResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateBookResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateBookResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateBookResp::clear_base() {
  if (base_ != NULL) base_->::book_mgr::BaseResp::Clear();
  clear_has_base();
}
inline const ::book_mgr::BaseResp& UpdateBookResp::base() const {
  // @@protoc_insertion_point(field_get:book_mgr.UpdateBookResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::book_mgr::BaseResp* UpdateBookResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::book_mgr::BaseResp;
  // @@protoc_insertion_point(field_mutable:book_mgr.UpdateBookResp.base)
  return base_;
}
inline ::book_mgr::BaseResp* UpdateBookResp::release_base() {
  clear_has_base();
  ::book_mgr::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void UpdateBookResp::set_allocated_base(::book_mgr::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.UpdateBookResp.base)
}

// -------------------------------------------------------------------

// DeleteBookReq

// optional string book_id = 1;
inline bool DeleteBookReq::has_book_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteBookReq::set_has_book_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteBookReq::clear_has_book_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteBookReq::clear_book_id() {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_->clear();
  }
  clear_has_book_id();
}
inline const ::std::string& DeleteBookReq::book_id() const {
  // @@protoc_insertion_point(field_get:book_mgr.DeleteBookReq.book_id)
  return *book_id_;
}
inline void DeleteBookReq::set_book_id(const ::std::string& value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set:book_mgr.DeleteBookReq.book_id)
}
inline void DeleteBookReq::set_book_id(const char* value) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:book_mgr.DeleteBookReq.book_id)
}
inline void DeleteBookReq::set_book_id(const char* value, size_t size) {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  book_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book_mgr.DeleteBookReq.book_id)
}
inline ::std::string* DeleteBookReq::mutable_book_id() {
  set_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    book_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:book_mgr.DeleteBookReq.book_id)
  return book_id_;
}
inline ::std::string* DeleteBookReq::release_book_id() {
  clear_has_book_id();
  if (book_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = book_id_;
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DeleteBookReq::set_allocated_book_id(::std::string* book_id) {
  if (book_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete book_id_;
  }
  if (book_id) {
    set_has_book_id();
    book_id_ = book_id;
  } else {
    clear_has_book_id();
    book_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.DeleteBookReq.book_id)
}

// -------------------------------------------------------------------

// DeleteBookResp

// optional .book_mgr.BaseResp base = 1;
inline bool DeleteBookResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteBookResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteBookResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteBookResp::clear_base() {
  if (base_ != NULL) base_->::book_mgr::BaseResp::Clear();
  clear_has_base();
}
inline const ::book_mgr::BaseResp& DeleteBookResp::base() const {
  // @@protoc_insertion_point(field_get:book_mgr.DeleteBookResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::book_mgr::BaseResp* DeleteBookResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::book_mgr::BaseResp;
  // @@protoc_insertion_point(field_mutable:book_mgr.DeleteBookResp.base)
  return base_;
}
inline ::book_mgr::BaseResp* DeleteBookResp::release_base() {
  clear_has_base();
  ::book_mgr::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void DeleteBookResp::set_allocated_base(::book_mgr::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.DeleteBookResp.base)
}

// -------------------------------------------------------------------

// BookReq

// optional .book_mgr.OpType op_type = 1;
inline bool BookReq::has_op_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BookReq::set_has_op_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BookReq::clear_has_op_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BookReq::clear_op_type() {
  op_type_ = 0;
  clear_has_op_type();
}
inline ::book_mgr::OpType BookReq::op_type() const {
  // @@protoc_insertion_point(field_get:book_mgr.BookReq.op_type)
  return static_cast< ::book_mgr::OpType >(op_type_);
}
inline void BookReq::set_op_type(::book_mgr::OpType value) {
  assert(::book_mgr::OpType_IsValid(value));
  set_has_op_type();
  op_type_ = value;
  // @@protoc_insertion_point(field_set:book_mgr.BookReq.op_type)
}

// optional .book_mgr.CreateBookReq create_req = 2;
inline bool BookReq::has_create_req() const {
  return req_body_case() == kCreateReq;
}
inline void BookReq::set_has_create_req() {
  _oneof_case_[0] = kCreateReq;
}
inline void BookReq::clear_create_req() {
  if (has_create_req()) {
    delete req_body_.create_req_;
    clear_has_req_body();
  }
}
inline const ::book_mgr::CreateBookReq& BookReq::create_req() const {
  return has_create_req() ? *req_body_.create_req_
                      : ::book_mgr::CreateBookReq::default_instance();
}
inline ::book_mgr::CreateBookReq* BookReq::mutable_create_req() {
  if (!has_create_req()) {
    clear_req_body();
    set_has_create_req();
    req_body_.create_req_ = new ::book_mgr::CreateBookReq;
  }
  return req_body_.create_req_;
}
inline ::book_mgr::CreateBookReq* BookReq::release_create_req() {
  if (has_create_req()) {
    clear_has_req_body();
    ::book_mgr::CreateBookReq* temp = req_body_.create_req_;
    req_body_.create_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookReq::set_allocated_create_req(::book_mgr::CreateBookReq* create_req) {
  clear_req_body();
  if (create_req) {
    set_has_create_req();
    req_body_.create_req_ = create_req;
  }
}

// optional .book_mgr.GetBookReq get_req = 3;
inline bool BookReq::has_get_req() const {
  return req_body_case() == kGetReq;
}
inline void BookReq::set_has_get_req() {
  _oneof_case_[0] = kGetReq;
}
inline void BookReq::clear_get_req() {
  if (has_get_req()) {
    delete req_body_.get_req_;
    clear_has_req_body();
  }
}
inline const ::book_mgr::GetBookReq& BookReq::get_req() const {
  return has_get_req() ? *req_body_.get_req_
                      : ::book_mgr::GetBookReq::default_instance();
}
inline ::book_mgr::GetBookReq* BookReq::mutable_get_req() {
  if (!has_get_req()) {
    clear_req_body();
    set_has_get_req();
    req_body_.get_req_ = new ::book_mgr::GetBookReq;
  }
  return req_body_.get_req_;
}
inline ::book_mgr::GetBookReq* BookReq::release_get_req() {
  if (has_get_req()) {
    clear_has_req_body();
    ::book_mgr::GetBookReq* temp = req_body_.get_req_;
    req_body_.get_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookReq::set_allocated_get_req(::book_mgr::GetBookReq* get_req) {
  clear_req_body();
  if (get_req) {
    set_has_get_req();
    req_body_.get_req_ = get_req;
  }
}

// optional .book_mgr.UpdateBookReq update_req = 4;
inline bool BookReq::has_update_req() const {
  return req_body_case() == kUpdateReq;
}
inline void BookReq::set_has_update_req() {
  _oneof_case_[0] = kUpdateReq;
}
inline void BookReq::clear_update_req() {
  if (has_update_req()) {
    delete req_body_.update_req_;
    clear_has_req_body();
  }
}
inline const ::book_mgr::UpdateBookReq& BookReq::update_req() const {
  return has_update_req() ? *req_body_.update_req_
                      : ::book_mgr::UpdateBookReq::default_instance();
}
inline ::book_mgr::UpdateBookReq* BookReq::mutable_update_req() {
  if (!has_update_req()) {
    clear_req_body();
    set_has_update_req();
    req_body_.update_req_ = new ::book_mgr::UpdateBookReq;
  }
  return req_body_.update_req_;
}
inline ::book_mgr::UpdateBookReq* BookReq::release_update_req() {
  if (has_update_req()) {
    clear_has_req_body();
    ::book_mgr::UpdateBookReq* temp = req_body_.update_req_;
    req_body_.update_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookReq::set_allocated_update_req(::book_mgr::UpdateBookReq* update_req) {
  clear_req_body();
  if (update_req) {
    set_has_update_req();
    req_body_.update_req_ = update_req;
  }
}

// optional .book_mgr.DeleteBookReq delete_req = 5;
inline bool BookReq::has_delete_req() const {
  return req_body_case() == kDeleteReq;
}
inline void BookReq::set_has_delete_req() {
  _oneof_case_[0] = kDeleteReq;
}
inline void BookReq::clear_delete_req() {
  if (has_delete_req()) {
    delete req_body_.delete_req_;
    clear_has_req_body();
  }
}
inline const ::book_mgr::DeleteBookReq& BookReq::delete_req() const {
  return has_delete_req() ? *req_body_.delete_req_
                      : ::book_mgr::DeleteBookReq::default_instance();
}
inline ::book_mgr::DeleteBookReq* BookReq::mutable_delete_req() {
  if (!has_delete_req()) {
    clear_req_body();
    set_has_delete_req();
    req_body_.delete_req_ = new ::book_mgr::DeleteBookReq;
  }
  return req_body_.delete_req_;
}
inline ::book_mgr::DeleteBookReq* BookReq::release_delete_req() {
  if (has_delete_req()) {
    clear_has_req_body();
    ::book_mgr::DeleteBookReq* temp = req_body_.delete_req_;
    req_body_.delete_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookReq::set_allocated_delete_req(::book_mgr::DeleteBookReq* delete_req) {
  clear_req_body();
  if (delete_req) {
    set_has_delete_req();
    req_body_.delete_req_ = delete_req;
  }
}

inline bool BookReq::has_req_body() {
  return req_body_case() != REQ_BODY_NOT_SET;
}
inline void BookReq::clear_has_req_body() {
  _oneof_case_[0] = REQ_BODY_NOT_SET;
}
inline BookReq::ReqBodyCase BookReq::req_body_case() const {
  return BookReq::ReqBodyCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// BookResp

// optional .book_mgr.BaseResp base = 1;
inline bool BookResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BookResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BookResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BookResp::clear_base() {
  if (base_ != NULL) base_->::book_mgr::BaseResp::Clear();
  clear_has_base();
}
inline const ::book_mgr::BaseResp& BookResp::base() const {
  // @@protoc_insertion_point(field_get:book_mgr.BookResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::book_mgr::BaseResp* BookResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::book_mgr::BaseResp;
  // @@protoc_insertion_point(field_mutable:book_mgr.BookResp.base)
  return base_;
}
inline ::book_mgr::BaseResp* BookResp::release_base() {
  clear_has_base();
  ::book_mgr::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void BookResp::set_allocated_base(::book_mgr::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:book_mgr.BookResp.base)
}

// optional .book_mgr.CreateBookResp create_resp = 2;
inline bool BookResp::has_create_resp() const {
  return resp_body_case() == kCreateResp;
}
inline void BookResp::set_has_create_resp() {
  _oneof_case_[0] = kCreateResp;
}
inline void BookResp::clear_create_resp() {
  if (has_create_resp()) {
    delete resp_body_.create_resp_;
    clear_has_resp_body();
  }
}
inline const ::book_mgr::CreateBookResp& BookResp::create_resp() const {
  return has_create_resp() ? *resp_body_.create_resp_
                      : ::book_mgr::CreateBookResp::default_instance();
}
inline ::book_mgr::CreateBookResp* BookResp::mutable_create_resp() {
  if (!has_create_resp()) {
    clear_resp_body();
    set_has_create_resp();
    resp_body_.create_resp_ = new ::book_mgr::CreateBookResp;
  }
  return resp_body_.create_resp_;
}
inline ::book_mgr::CreateBookResp* BookResp::release_create_resp() {
  if (has_create_resp()) {
    clear_has_resp_body();
    ::book_mgr::CreateBookResp* temp = resp_body_.create_resp_;
    resp_body_.create_resp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookResp::set_allocated_create_resp(::book_mgr::CreateBookResp* create_resp) {
  clear_resp_body();
  if (create_resp) {
    set_has_create_resp();
    resp_body_.create_resp_ = create_resp;
  }
}

// optional .book_mgr.GetBookResp get_resp = 3;
inline bool BookResp::has_get_resp() const {
  return resp_body_case() == kGetResp;
}
inline void BookResp::set_has_get_resp() {
  _oneof_case_[0] = kGetResp;
}
inline void BookResp::clear_get_resp() {
  if (has_get_resp()) {
    delete resp_body_.get_resp_;
    clear_has_resp_body();
  }
}
inline const ::book_mgr::GetBookResp& BookResp::get_resp() const {
  return has_get_resp() ? *resp_body_.get_resp_
                      : ::book_mgr::GetBookResp::default_instance();
}
inline ::book_mgr::GetBookResp* BookResp::mutable_get_resp() {
  if (!has_get_resp()) {
    clear_resp_body();
    set_has_get_resp();
    resp_body_.get_resp_ = new ::book_mgr::GetBookResp;
  }
  return resp_body_.get_resp_;
}
inline ::book_mgr::GetBookResp* BookResp::release_get_resp() {
  if (has_get_resp()) {
    clear_has_resp_body();
    ::book_mgr::GetBookResp* temp = resp_body_.get_resp_;
    resp_body_.get_resp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookResp::set_allocated_get_resp(::book_mgr::GetBookResp* get_resp) {
  clear_resp_body();
  if (get_resp) {
    set_has_get_resp();
    resp_body_.get_resp_ = get_resp;
  }
}

// optional .book_mgr.UpdateBookResp update_resp = 4;
inline bool BookResp::has_update_resp() const {
  return resp_body_case() == kUpdateResp;
}
inline void BookResp::set_has_update_resp() {
  _oneof_case_[0] = kUpdateResp;
}
inline void BookResp::clear_update_resp() {
  if (has_update_resp()) {
    delete resp_body_.update_resp_;
    clear_has_resp_body();
  }
}
inline const ::book_mgr::UpdateBookResp& BookResp::update_resp() const {
  return has_update_resp() ? *resp_body_.update_resp_
                      : ::book_mgr::UpdateBookResp::default_instance();
}
inline ::book_mgr::UpdateBookResp* BookResp::mutable_update_resp() {
  if (!has_update_resp()) {
    clear_resp_body();
    set_has_update_resp();
    resp_body_.update_resp_ = new ::book_mgr::UpdateBookResp;
  }
  return resp_body_.update_resp_;
}
inline ::book_mgr::UpdateBookResp* BookResp::release_update_resp() {
  if (has_update_resp()) {
    clear_has_resp_body();
    ::book_mgr::UpdateBookResp* temp = resp_body_.update_resp_;
    resp_body_.update_resp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookResp::set_allocated_update_resp(::book_mgr::UpdateBookResp* update_resp) {
  clear_resp_body();
  if (update_resp) {
    set_has_update_resp();
    resp_body_.update_resp_ = update_resp;
  }
}

// optional .book_mgr.DeleteBookResp delete_resp = 5;
inline bool BookResp::has_delete_resp() const {
  return resp_body_case() == kDeleteResp;
}
inline void BookResp::set_has_delete_resp() {
  _oneof_case_[0] = kDeleteResp;
}
inline void BookResp::clear_delete_resp() {
  if (has_delete_resp()) {
    delete resp_body_.delete_resp_;
    clear_has_resp_body();
  }
}
inline const ::book_mgr::DeleteBookResp& BookResp::delete_resp() const {
  return has_delete_resp() ? *resp_body_.delete_resp_
                      : ::book_mgr::DeleteBookResp::default_instance();
}
inline ::book_mgr::DeleteBookResp* BookResp::mutable_delete_resp() {
  if (!has_delete_resp()) {
    clear_resp_body();
    set_has_delete_resp();
    resp_body_.delete_resp_ = new ::book_mgr::DeleteBookResp;
  }
  return resp_body_.delete_resp_;
}
inline ::book_mgr::DeleteBookResp* BookResp::release_delete_resp() {
  if (has_delete_resp()) {
    clear_has_resp_body();
    ::book_mgr::DeleteBookResp* temp = resp_body_.delete_resp_;
    resp_body_.delete_resp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void BookResp::set_allocated_delete_resp(::book_mgr::DeleteBookResp* delete_resp) {
  clear_resp_body();
  if (delete_resp) {
    set_has_delete_resp();
    resp_body_.delete_resp_ = delete_resp;
  }
}

inline bool BookResp::has_resp_body() {
  return resp_body_case() != RESP_BODY_NOT_SET;
}
inline void BookResp::clear_has_resp_body() {
  _oneof_case_[0] = RESP_BODY_NOT_SET;
}
inline BookResp::RespBodyCase BookResp::resp_body_case() const {
  return BookResp::RespBodyCase(_oneof_case_[0]);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace book_mgr

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::book_mgr::OpType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::book_mgr::OpType>() {
  return ::book_mgr::OpType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_book_2eproto__INCLUDED
