// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_multi.proto

#ifndef PROTOBUF_demo_5fmulti_2eproto__INCLUDED
#define PROTOBUF_demo_5fmulti_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace demo_multi {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_demo_5fmulti_2eproto();
void protobuf_AssignDesc_demo_5fmulti_2eproto();
void protobuf_ShutdownFile_demo_5fmulti_2eproto();

class BaseResp;
class AclReq;
class AclResp;
class StudyReq;
class StudyResp;
class ControlReq;
class ControlResp;
class ClientReq;
class ClientResp;

// ===================================================================

class BaseResp : public ::google::protobuf::Message {
 public:
  BaseResp();
  virtual ~BaseResp();

  BaseResp(const BaseResp& from);

  inline BaseResp& operator=(const BaseResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseResp& default_instance();

  void Swap(BaseResp* other);

  // implements Message ----------------------------------------------

  BaseResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseResp& from);
  void MergeFrom(const BaseResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ret_code = 1;
  inline bool has_ret_code() const;
  inline void clear_ret_code();
  static const int kRetCodeFieldNumber = 1;
  inline ::google::protobuf::int32 ret_code() const;
  inline void set_ret_code(::google::protobuf::int32 value);

  // optional string ret_msg = 2;
  inline bool has_ret_msg() const;
  inline void clear_ret_msg();
  static const int kRetMsgFieldNumber = 2;
  inline const ::std::string& ret_msg() const;
  inline void set_ret_msg(const ::std::string& value);
  inline void set_ret_msg(const char* value);
  inline void set_ret_msg(const char* value, size_t size);
  inline ::std::string* mutable_ret_msg();
  inline ::std::string* release_ret_msg();
  inline void set_allocated_ret_msg(::std::string* ret_msg);

  // @@protoc_insertion_point(class_scope:demo_multi.BaseResp)
 private:
  inline void set_has_ret_code();
  inline void clear_has_ret_code();
  inline void set_has_ret_msg();
  inline void clear_has_ret_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* ret_msg_;
  ::google::protobuf::int32 ret_code_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static BaseResp* default_instance_;
};
// -------------------------------------------------------------------

class AclReq : public ::google::protobuf::Message {
 public:
  AclReq();
  virtual ~AclReq();

  AclReq(const AclReq& from);

  inline AclReq& operator=(const AclReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AclReq& default_instance();

  void Swap(AclReq* other);

  // implements Message ----------------------------------------------

  AclReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AclReq& from);
  void MergeFrom(const AclReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string user_name = 1;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // optional string resource = 2;
  inline bool has_resource() const;
  inline void clear_resource();
  static const int kResourceFieldNumber = 2;
  inline const ::std::string& resource() const;
  inline void set_resource(const ::std::string& value);
  inline void set_resource(const char* value);
  inline void set_resource(const char* value, size_t size);
  inline ::std::string* mutable_resource();
  inline ::std::string* release_resource();
  inline void set_allocated_resource(::std::string* resource);

  // @@protoc_insertion_point(class_scope:demo_multi.AclReq)
 private:
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_resource();
  inline void clear_has_resource();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* user_name_;
  ::std::string* resource_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static AclReq* default_instance_;
};
// -------------------------------------------------------------------

class AclResp : public ::google::protobuf::Message {
 public:
  AclResp();
  virtual ~AclResp();

  AclResp(const AclResp& from);

  inline AclResp& operator=(const AclResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AclResp& default_instance();

  void Swap(AclResp* other);

  // implements Message ----------------------------------------------

  AclResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AclResp& from);
  void MergeFrom(const AclResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .demo_multi.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::demo_multi::BaseResp& base() const;
  inline ::demo_multi::BaseResp* mutable_base();
  inline ::demo_multi::BaseResp* release_base();
  inline void set_allocated_base(::demo_multi::BaseResp* base);

  // optional bool is_allow = 2;
  inline bool has_is_allow() const;
  inline void clear_is_allow();
  static const int kIsAllowFieldNumber = 2;
  inline bool is_allow() const;
  inline void set_is_allow(bool value);

  // optional string detail = 3;
  inline bool has_detail() const;
  inline void clear_detail();
  static const int kDetailFieldNumber = 3;
  inline const ::std::string& detail() const;
  inline void set_detail(const ::std::string& value);
  inline void set_detail(const char* value);
  inline void set_detail(const char* value, size_t size);
  inline ::std::string* mutable_detail();
  inline ::std::string* release_detail();
  inline void set_allocated_detail(::std::string* detail);

  // @@protoc_insertion_point(class_scope:demo_multi.AclResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_is_allow();
  inline void clear_has_is_allow();
  inline void set_has_detail();
  inline void clear_has_detail();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::demo_multi::BaseResp* base_;
  ::std::string* detail_;
  bool is_allow_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static AclResp* default_instance_;
};
// -------------------------------------------------------------------

class StudyReq : public ::google::protobuf::Message {
 public:
  StudyReq();
  virtual ~StudyReq();

  StudyReq(const StudyReq& from);

  inline StudyReq& operator=(const StudyReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StudyReq& default_instance();

  void Swap(StudyReq* other);

  // implements Message ----------------------------------------------

  StudyReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StudyReq& from);
  void MergeFrom(const StudyReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string student_name = 1;
  inline bool has_student_name() const;
  inline void clear_student_name();
  static const int kStudentNameFieldNumber = 1;
  inline const ::std::string& student_name() const;
  inline void set_student_name(const ::std::string& value);
  inline void set_student_name(const char* value);
  inline void set_student_name(const char* value, size_t size);
  inline ::std::string* mutable_student_name();
  inline ::std::string* release_student_name();
  inline void set_allocated_student_name(::std::string* student_name);

  // optional string subject = 2;
  inline bool has_subject() const;
  inline void clear_subject();
  static const int kSubjectFieldNumber = 2;
  inline const ::std::string& subject() const;
  inline void set_subject(const ::std::string& value);
  inline void set_subject(const char* value);
  inline void set_subject(const char* value, size_t size);
  inline ::std::string* mutable_subject();
  inline ::std::string* release_subject();
  inline void set_allocated_subject(::std::string* subject);

  // @@protoc_insertion_point(class_scope:demo_multi.StudyReq)
 private:
  inline void set_has_student_name();
  inline void clear_has_student_name();
  inline void set_has_subject();
  inline void clear_has_subject();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* student_name_;
  ::std::string* subject_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static StudyReq* default_instance_;
};
// -------------------------------------------------------------------

class StudyResp : public ::google::protobuf::Message {
 public:
  StudyResp();
  virtual ~StudyResp();

  StudyResp(const StudyResp& from);

  inline StudyResp& operator=(const StudyResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StudyResp& default_instance();

  void Swap(StudyResp* other);

  // implements Message ----------------------------------------------

  StudyResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StudyResp& from);
  void MergeFrom(const StudyResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .demo_multi.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::demo_multi::BaseResp& base() const;
  inline ::demo_multi::BaseResp* mutable_base();
  inline ::demo_multi::BaseResp* release_base();
  inline void set_allocated_base(::demo_multi::BaseResp* base);

  // optional int32 num_subject = 2;
  inline bool has_num_subject() const;
  inline void clear_num_subject();
  static const int kNumSubjectFieldNumber = 2;
  inline ::google::protobuf::int32 num_subject() const;
  inline void set_num_subject(::google::protobuf::int32 value);

  // optional string detail = 3;
  inline bool has_detail() const;
  inline void clear_detail();
  static const int kDetailFieldNumber = 3;
  inline const ::std::string& detail() const;
  inline void set_detail(const ::std::string& value);
  inline void set_detail(const char* value);
  inline void set_detail(const char* value, size_t size);
  inline ::std::string* mutable_detail();
  inline ::std::string* release_detail();
  inline void set_allocated_detail(::std::string* detail);

  // @@protoc_insertion_point(class_scope:demo_multi.StudyResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_num_subject();
  inline void clear_has_num_subject();
  inline void set_has_detail();
  inline void clear_has_detail();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::demo_multi::BaseResp* base_;
  ::std::string* detail_;
  ::google::protobuf::int32 num_subject_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static StudyResp* default_instance_;
};
// -------------------------------------------------------------------

class ControlReq : public ::google::protobuf::Message {
 public:
  ControlReq();
  virtual ~ControlReq();

  ControlReq(const ControlReq& from);

  inline ControlReq& operator=(const ControlReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlReq& default_instance();

  void Swap(ControlReq* other);

  // implements Message ----------------------------------------------

  ControlReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ControlReq& from);
  void MergeFrom(const ControlReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string command = 1;
  inline bool has_command() const;
  inline void clear_command();
  static const int kCommandFieldNumber = 1;
  inline const ::std::string& command() const;
  inline void set_command(const ::std::string& value);
  inline void set_command(const char* value);
  inline void set_command(const char* value, size_t size);
  inline ::std::string* mutable_command();
  inline ::std::string* release_command();
  inline void set_allocated_command(::std::string* command);

  // optional string target = 2;
  inline bool has_target() const;
  inline void clear_target();
  static const int kTargetFieldNumber = 2;
  inline const ::std::string& target() const;
  inline void set_target(const ::std::string& value);
  inline void set_target(const char* value);
  inline void set_target(const char* value, size_t size);
  inline ::std::string* mutable_target();
  inline ::std::string* release_target();
  inline void set_allocated_target(::std::string* target);

  // @@protoc_insertion_point(class_scope:demo_multi.ControlReq)
 private:
  inline void set_has_command();
  inline void clear_has_command();
  inline void set_has_target();
  inline void clear_has_target();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* command_;
  ::std::string* target_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static ControlReq* default_instance_;
};
// -------------------------------------------------------------------

class ControlResp : public ::google::protobuf::Message {
 public:
  ControlResp();
  virtual ~ControlResp();

  ControlResp(const ControlResp& from);

  inline ControlResp& operator=(const ControlResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlResp& default_instance();

  void Swap(ControlResp* other);

  // implements Message ----------------------------------------------

  ControlResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ControlResp& from);
  void MergeFrom(const ControlResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .demo_multi.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::demo_multi::BaseResp& base() const;
  inline ::demo_multi::BaseResp* mutable_base();
  inline ::demo_multi::BaseResp* release_base();
  inline void set_allocated_base(::demo_multi::BaseResp* base);

  // optional string acl_result = 2;
  inline bool has_acl_result() const;
  inline void clear_acl_result();
  static const int kAclResultFieldNumber = 2;
  inline const ::std::string& acl_result() const;
  inline void set_acl_result(const ::std::string& value);
  inline void set_acl_result(const char* value);
  inline void set_acl_result(const char* value, size_t size);
  inline ::std::string* mutable_acl_result();
  inline ::std::string* release_acl_result();
  inline void set_allocated_acl_result(::std::string* acl_result);

  // optional string study_result = 3;
  inline bool has_study_result() const;
  inline void clear_study_result();
  static const int kStudyResultFieldNumber = 3;
  inline const ::std::string& study_result() const;
  inline void set_study_result(const ::std::string& value);
  inline void set_study_result(const char* value);
  inline void set_study_result(const char* value, size_t size);
  inline ::std::string* mutable_study_result();
  inline ::std::string* release_study_result();
  inline void set_allocated_study_result(::std::string* study_result);

  // @@protoc_insertion_point(class_scope:demo_multi.ControlResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_acl_result();
  inline void clear_has_acl_result();
  inline void set_has_study_result();
  inline void clear_has_study_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::demo_multi::BaseResp* base_;
  ::std::string* acl_result_;
  ::std::string* study_result_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static ControlResp* default_instance_;
};
// -------------------------------------------------------------------

class ClientReq : public ::google::protobuf::Message {
 public:
  ClientReq();
  virtual ~ClientReq();

  ClientReq(const ClientReq& from);

  inline ClientReq& operator=(const ClientReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientReq& default_instance();

  void Swap(ClientReq* other);

  // implements Message ----------------------------------------------

  ClientReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientReq& from);
  void MergeFrom(const ClientReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string message = 1;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 1;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional int32 index = 2;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 2;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:demo_multi.ClientReq)
 private:
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_index();
  inline void clear_has_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* message_;
  ::google::protobuf::int32 index_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static ClientReq* default_instance_;
};
// -------------------------------------------------------------------

class ClientResp : public ::google::protobuf::Message {
 public:
  ClientResp();
  virtual ~ClientResp();

  ClientResp(const ClientResp& from);

  inline ClientResp& operator=(const ClientResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientResp& default_instance();

  void Swap(ClientResp* other);

  // implements Message ----------------------------------------------

  ClientResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientResp& from);
  void MergeFrom(const ClientResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .demo_multi.BaseResp base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::demo_multi::BaseResp& base() const;
  inline ::demo_multi::BaseResp* mutable_base();
  inline ::demo_multi::BaseResp* release_base();
  inline void set_allocated_base(::demo_multi::BaseResp* base);

  // optional string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:demo_multi.ClientResp)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::demo_multi::BaseResp* base_;
  ::std::string* message_;
  friend void  protobuf_AddDesc_demo_5fmulti_2eproto();
  friend void protobuf_AssignDesc_demo_5fmulti_2eproto();
  friend void protobuf_ShutdownFile_demo_5fmulti_2eproto();

  void InitAsDefaultInstance();
  static ClientResp* default_instance_;
};
// ===================================================================


// ===================================================================

// BaseResp

// optional int32 ret_code = 1;
inline bool BaseResp::has_ret_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseResp::set_has_ret_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseResp::clear_has_ret_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseResp::clear_ret_code() {
  ret_code_ = 0;
  clear_has_ret_code();
}
inline ::google::protobuf::int32 BaseResp::ret_code() const {
  // @@protoc_insertion_point(field_get:demo_multi.BaseResp.ret_code)
  return ret_code_;
}
inline void BaseResp::set_ret_code(::google::protobuf::int32 value) {
  set_has_ret_code();
  ret_code_ = value;
  // @@protoc_insertion_point(field_set:demo_multi.BaseResp.ret_code)
}

// optional string ret_msg = 2;
inline bool BaseResp::has_ret_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BaseResp::set_has_ret_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BaseResp::clear_has_ret_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BaseResp::clear_ret_msg() {
  if (ret_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_->clear();
  }
  clear_has_ret_msg();
}
inline const ::std::string& BaseResp::ret_msg() const {
  // @@protoc_insertion_point(field_get:demo_multi.BaseResp.ret_msg)
  return *ret_msg_;
}
inline void BaseResp::set_ret_msg(const ::std::string& value) {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  ret_msg_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.BaseResp.ret_msg)
}
inline void BaseResp::set_ret_msg(const char* value) {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  ret_msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.BaseResp.ret_msg)
}
inline void BaseResp::set_ret_msg(const char* value, size_t size) {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  ret_msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.BaseResp.ret_msg)
}
inline ::std::string* BaseResp::mutable_ret_msg() {
  set_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.BaseResp.ret_msg)
  return ret_msg_;
}
inline ::std::string* BaseResp::release_ret_msg() {
  clear_has_ret_msg();
  if (ret_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ret_msg_;
    ret_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void BaseResp::set_allocated_ret_msg(::std::string* ret_msg) {
  if (ret_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ret_msg_;
  }
  if (ret_msg) {
    set_has_ret_msg();
    ret_msg_ = ret_msg;
  } else {
    clear_has_ret_msg();
    ret_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.BaseResp.ret_msg)
}

// -------------------------------------------------------------------

// AclReq

// optional string user_name = 1;
inline bool AclReq::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AclReq::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AclReq::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AclReq::clear_user_name() {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_->clear();
  }
  clear_has_user_name();
}
inline const ::std::string& AclReq::user_name() const {
  // @@protoc_insertion_point(field_get:demo_multi.AclReq.user_name)
  return *user_name_;
}
inline void AclReq::set_user_name(const ::std::string& value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.AclReq.user_name)
}
inline void AclReq::set_user_name(const char* value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.AclReq.user_name)
}
inline void AclReq::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.AclReq.user_name)
}
inline ::std::string* AclReq::mutable_user_name() {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.AclReq.user_name)
  return user_name_;
}
inline ::std::string* AclReq::release_user_name() {
  clear_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = user_name_;
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AclReq::set_allocated_user_name(::std::string* user_name) {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete user_name_;
  }
  if (user_name) {
    set_has_user_name();
    user_name_ = user_name;
  } else {
    clear_has_user_name();
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.AclReq.user_name)
}

// optional string resource = 2;
inline bool AclReq::has_resource() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AclReq::set_has_resource() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AclReq::clear_has_resource() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AclReq::clear_resource() {
  if (resource_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_->clear();
  }
  clear_has_resource();
}
inline const ::std::string& AclReq::resource() const {
  // @@protoc_insertion_point(field_get:demo_multi.AclReq.resource)
  return *resource_;
}
inline void AclReq::set_resource(const ::std::string& value) {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  resource_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.AclReq.resource)
}
inline void AclReq::set_resource(const char* value) {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  resource_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.AclReq.resource)
}
inline void AclReq::set_resource(const char* value, size_t size) {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  resource_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.AclReq.resource)
}
inline ::std::string* AclReq::mutable_resource() {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.AclReq.resource)
  return resource_;
}
inline ::std::string* AclReq::release_resource() {
  clear_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = resource_;
    resource_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AclReq::set_allocated_resource(::std::string* resource) {
  if (resource_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete resource_;
  }
  if (resource) {
    set_has_resource();
    resource_ = resource;
  } else {
    clear_has_resource();
    resource_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.AclReq.resource)
}

// -------------------------------------------------------------------

// AclResp

// optional .demo_multi.BaseResp base = 1;
inline bool AclResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AclResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AclResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AclResp::clear_base() {
  if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
  clear_has_base();
}
inline const ::demo_multi::BaseResp& AclResp::base() const {
  // @@protoc_insertion_point(field_get:demo_multi.AclResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::demo_multi::BaseResp* AclResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::demo_multi::BaseResp;
  // @@protoc_insertion_point(field_mutable:demo_multi.AclResp.base)
  return base_;
}
inline ::demo_multi::BaseResp* AclResp::release_base() {
  clear_has_base();
  ::demo_multi::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void AclResp::set_allocated_base(::demo_multi::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.AclResp.base)
}

// optional bool is_allow = 2;
inline bool AclResp::has_is_allow() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AclResp::set_has_is_allow() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AclResp::clear_has_is_allow() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AclResp::clear_is_allow() {
  is_allow_ = false;
  clear_has_is_allow();
}
inline bool AclResp::is_allow() const {
  // @@protoc_insertion_point(field_get:demo_multi.AclResp.is_allow)
  return is_allow_;
}
inline void AclResp::set_is_allow(bool value) {
  set_has_is_allow();
  is_allow_ = value;
  // @@protoc_insertion_point(field_set:demo_multi.AclResp.is_allow)
}

// optional string detail = 3;
inline bool AclResp::has_detail() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AclResp::set_has_detail() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AclResp::clear_has_detail() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AclResp::clear_detail() {
  if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_->clear();
  }
  clear_has_detail();
}
inline const ::std::string& AclResp::detail() const {
  // @@protoc_insertion_point(field_get:demo_multi.AclResp.detail)
  return *detail_;
}
inline void AclResp::set_detail(const ::std::string& value) {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  detail_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.AclResp.detail)
}
inline void AclResp::set_detail(const char* value) {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  detail_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.AclResp.detail)
}
inline void AclResp::set_detail(const char* value, size_t size) {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  detail_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.AclResp.detail)
}
inline ::std::string* AclResp::mutable_detail() {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.AclResp.detail)
  return detail_;
}
inline ::std::string* AclResp::release_detail() {
  clear_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = detail_;
    detail_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AclResp::set_allocated_detail(::std::string* detail) {
  if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete detail_;
  }
  if (detail) {
    set_has_detail();
    detail_ = detail;
  } else {
    clear_has_detail();
    detail_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.AclResp.detail)
}

// -------------------------------------------------------------------

// StudyReq

// optional string student_name = 1;
inline bool StudyReq::has_student_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StudyReq::set_has_student_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StudyReq::clear_has_student_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StudyReq::clear_student_name() {
  if (student_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    student_name_->clear();
  }
  clear_has_student_name();
}
inline const ::std::string& StudyReq::student_name() const {
  // @@protoc_insertion_point(field_get:demo_multi.StudyReq.student_name)
  return *student_name_;
}
inline void StudyReq::set_student_name(const ::std::string& value) {
  set_has_student_name();
  if (student_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    student_name_ = new ::std::string;
  }
  student_name_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.StudyReq.student_name)
}
inline void StudyReq::set_student_name(const char* value) {
  set_has_student_name();
  if (student_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    student_name_ = new ::std::string;
  }
  student_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.StudyReq.student_name)
}
inline void StudyReq::set_student_name(const char* value, size_t size) {
  set_has_student_name();
  if (student_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    student_name_ = new ::std::string;
  }
  student_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.StudyReq.student_name)
}
inline ::std::string* StudyReq::mutable_student_name() {
  set_has_student_name();
  if (student_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    student_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.StudyReq.student_name)
  return student_name_;
}
inline ::std::string* StudyReq::release_student_name() {
  clear_has_student_name();
  if (student_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = student_name_;
    student_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void StudyReq::set_allocated_student_name(::std::string* student_name) {
  if (student_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete student_name_;
  }
  if (student_name) {
    set_has_student_name();
    student_name_ = student_name;
  } else {
    clear_has_student_name();
    student_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.StudyReq.student_name)
}

// optional string subject = 2;
inline bool StudyReq::has_subject() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StudyReq::set_has_subject() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StudyReq::clear_has_subject() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StudyReq::clear_subject() {
  if (subject_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_->clear();
  }
  clear_has_subject();
}
inline const ::std::string& StudyReq::subject() const {
  // @@protoc_insertion_point(field_get:demo_multi.StudyReq.subject)
  return *subject_;
}
inline void StudyReq::set_subject(const ::std::string& value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.StudyReq.subject)
}
inline void StudyReq::set_subject(const char* value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.StudyReq.subject)
}
inline void StudyReq::set_subject(const char* value, size_t size) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  subject_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.StudyReq.subject)
}
inline ::std::string* StudyReq::mutable_subject() {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.StudyReq.subject)
  return subject_;
}
inline ::std::string* StudyReq::release_subject() {
  clear_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = subject_;
    subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void StudyReq::set_allocated_subject(::std::string* subject) {
  if (subject_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete subject_;
  }
  if (subject) {
    set_has_subject();
    subject_ = subject;
  } else {
    clear_has_subject();
    subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.StudyReq.subject)
}

// -------------------------------------------------------------------

// StudyResp

// optional .demo_multi.BaseResp base = 1;
inline bool StudyResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StudyResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StudyResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StudyResp::clear_base() {
  if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
  clear_has_base();
}
inline const ::demo_multi::BaseResp& StudyResp::base() const {
  // @@protoc_insertion_point(field_get:demo_multi.StudyResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::demo_multi::BaseResp* StudyResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::demo_multi::BaseResp;
  // @@protoc_insertion_point(field_mutable:demo_multi.StudyResp.base)
  return base_;
}
inline ::demo_multi::BaseResp* StudyResp::release_base() {
  clear_has_base();
  ::demo_multi::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void StudyResp::set_allocated_base(::demo_multi::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.StudyResp.base)
}

// optional int32 num_subject = 2;
inline bool StudyResp::has_num_subject() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StudyResp::set_has_num_subject() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StudyResp::clear_has_num_subject() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StudyResp::clear_num_subject() {
  num_subject_ = 0;
  clear_has_num_subject();
}
inline ::google::protobuf::int32 StudyResp::num_subject() const {
  // @@protoc_insertion_point(field_get:demo_multi.StudyResp.num_subject)
  return num_subject_;
}
inline void StudyResp::set_num_subject(::google::protobuf::int32 value) {
  set_has_num_subject();
  num_subject_ = value;
  // @@protoc_insertion_point(field_set:demo_multi.StudyResp.num_subject)
}

// optional string detail = 3;
inline bool StudyResp::has_detail() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StudyResp::set_has_detail() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StudyResp::clear_has_detail() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StudyResp::clear_detail() {
  if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_->clear();
  }
  clear_has_detail();
}
inline const ::std::string& StudyResp::detail() const {
  // @@protoc_insertion_point(field_get:demo_multi.StudyResp.detail)
  return *detail_;
}
inline void StudyResp::set_detail(const ::std::string& value) {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  detail_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.StudyResp.detail)
}
inline void StudyResp::set_detail(const char* value) {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  detail_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.StudyResp.detail)
}
inline void StudyResp::set_detail(const char* value, size_t size) {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  detail_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.StudyResp.detail)
}
inline ::std::string* StudyResp::mutable_detail() {
  set_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    detail_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.StudyResp.detail)
  return detail_;
}
inline ::std::string* StudyResp::release_detail() {
  clear_has_detail();
  if (detail_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = detail_;
    detail_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void StudyResp::set_allocated_detail(::std::string* detail) {
  if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete detail_;
  }
  if (detail) {
    set_has_detail();
    detail_ = detail;
  } else {
    clear_has_detail();
    detail_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.StudyResp.detail)
}

// -------------------------------------------------------------------

// ControlReq

// optional string command = 1;
inline bool ControlReq::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ControlReq::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ControlReq::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ControlReq::clear_command() {
  if (command_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_->clear();
  }
  clear_has_command();
}
inline const ::std::string& ControlReq::command() const {
  // @@protoc_insertion_point(field_get:demo_multi.ControlReq.command)
  return *command_;
}
inline void ControlReq::set_command(const ::std::string& value) {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  command_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.ControlReq.command)
}
inline void ControlReq::set_command(const char* value) {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  command_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.ControlReq.command)
}
inline void ControlReq::set_command(const char* value, size_t size) {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  command_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.ControlReq.command)
}
inline ::std::string* ControlReq::mutable_command() {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.ControlReq.command)
  return command_;
}
inline ::std::string* ControlReq::release_command() {
  clear_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = command_;
    command_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ControlReq::set_allocated_command(::std::string* command) {
  if (command_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete command_;
  }
  if (command) {
    set_has_command();
    command_ = command;
  } else {
    clear_has_command();
    command_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ControlReq.command)
}

// optional string target = 2;
inline bool ControlReq::has_target() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ControlReq::set_has_target() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ControlReq::clear_has_target() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ControlReq::clear_target() {
  if (target_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_->clear();
  }
  clear_has_target();
}
inline const ::std::string& ControlReq::target() const {
  // @@protoc_insertion_point(field_get:demo_multi.ControlReq.target)
  return *target_;
}
inline void ControlReq::set_target(const ::std::string& value) {
  set_has_target();
  if (target_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_ = new ::std::string;
  }
  target_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.ControlReq.target)
}
inline void ControlReq::set_target(const char* value) {
  set_has_target();
  if (target_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_ = new ::std::string;
  }
  target_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.ControlReq.target)
}
inline void ControlReq::set_target(const char* value, size_t size) {
  set_has_target();
  if (target_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_ = new ::std::string;
  }
  target_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.ControlReq.target)
}
inline ::std::string* ControlReq::mutable_target() {
  set_has_target();
  if (target_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.ControlReq.target)
  return target_;
}
inline ::std::string* ControlReq::release_target() {
  clear_has_target();
  if (target_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = target_;
    target_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ControlReq::set_allocated_target(::std::string* target) {
  if (target_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_;
  }
  if (target) {
    set_has_target();
    target_ = target;
  } else {
    clear_has_target();
    target_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ControlReq.target)
}

// -------------------------------------------------------------------

// ControlResp

// optional .demo_multi.BaseResp base = 1;
inline bool ControlResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ControlResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ControlResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ControlResp::clear_base() {
  if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
  clear_has_base();
}
inline const ::demo_multi::BaseResp& ControlResp::base() const {
  // @@protoc_insertion_point(field_get:demo_multi.ControlResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::demo_multi::BaseResp* ControlResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::demo_multi::BaseResp;
  // @@protoc_insertion_point(field_mutable:demo_multi.ControlResp.base)
  return base_;
}
inline ::demo_multi::BaseResp* ControlResp::release_base() {
  clear_has_base();
  ::demo_multi::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void ControlResp::set_allocated_base(::demo_multi::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ControlResp.base)
}

// optional string acl_result = 2;
inline bool ControlResp::has_acl_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ControlResp::set_has_acl_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ControlResp::clear_has_acl_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ControlResp::clear_acl_result() {
  if (acl_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    acl_result_->clear();
  }
  clear_has_acl_result();
}
inline const ::std::string& ControlResp::acl_result() const {
  // @@protoc_insertion_point(field_get:demo_multi.ControlResp.acl_result)
  return *acl_result_;
}
inline void ControlResp::set_acl_result(const ::std::string& value) {
  set_has_acl_result();
  if (acl_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    acl_result_ = new ::std::string;
  }
  acl_result_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.ControlResp.acl_result)
}
inline void ControlResp::set_acl_result(const char* value) {
  set_has_acl_result();
  if (acl_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    acl_result_ = new ::std::string;
  }
  acl_result_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.ControlResp.acl_result)
}
inline void ControlResp::set_acl_result(const char* value, size_t size) {
  set_has_acl_result();
  if (acl_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    acl_result_ = new ::std::string;
  }
  acl_result_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.ControlResp.acl_result)
}
inline ::std::string* ControlResp::mutable_acl_result() {
  set_has_acl_result();
  if (acl_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    acl_result_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.ControlResp.acl_result)
  return acl_result_;
}
inline ::std::string* ControlResp::release_acl_result() {
  clear_has_acl_result();
  if (acl_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = acl_result_;
    acl_result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ControlResp::set_allocated_acl_result(::std::string* acl_result) {
  if (acl_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete acl_result_;
  }
  if (acl_result) {
    set_has_acl_result();
    acl_result_ = acl_result;
  } else {
    clear_has_acl_result();
    acl_result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ControlResp.acl_result)
}

// optional string study_result = 3;
inline bool ControlResp::has_study_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ControlResp::set_has_study_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ControlResp::clear_has_study_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ControlResp::clear_study_result() {
  if (study_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    study_result_->clear();
  }
  clear_has_study_result();
}
inline const ::std::string& ControlResp::study_result() const {
  // @@protoc_insertion_point(field_get:demo_multi.ControlResp.study_result)
  return *study_result_;
}
inline void ControlResp::set_study_result(const ::std::string& value) {
  set_has_study_result();
  if (study_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    study_result_ = new ::std::string;
  }
  study_result_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.ControlResp.study_result)
}
inline void ControlResp::set_study_result(const char* value) {
  set_has_study_result();
  if (study_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    study_result_ = new ::std::string;
  }
  study_result_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.ControlResp.study_result)
}
inline void ControlResp::set_study_result(const char* value, size_t size) {
  set_has_study_result();
  if (study_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    study_result_ = new ::std::string;
  }
  study_result_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.ControlResp.study_result)
}
inline ::std::string* ControlResp::mutable_study_result() {
  set_has_study_result();
  if (study_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    study_result_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.ControlResp.study_result)
  return study_result_;
}
inline ::std::string* ControlResp::release_study_result() {
  clear_has_study_result();
  if (study_result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = study_result_;
    study_result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ControlResp::set_allocated_study_result(::std::string* study_result) {
  if (study_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete study_result_;
  }
  if (study_result) {
    set_has_study_result();
    study_result_ = study_result;
  } else {
    clear_has_study_result();
    study_result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ControlResp.study_result)
}

// -------------------------------------------------------------------

// ClientReq

// optional string message = 1;
inline bool ClientReq::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientReq::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientReq::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientReq::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& ClientReq::message() const {
  // @@protoc_insertion_point(field_get:demo_multi.ClientReq.message)
  return *message_;
}
inline void ClientReq::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.ClientReq.message)
}
inline void ClientReq::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.ClientReq.message)
}
inline void ClientReq::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.ClientReq.message)
}
inline ::std::string* ClientReq::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.ClientReq.message)
  return message_;
}
inline ::std::string* ClientReq::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ClientReq::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ClientReq.message)
}

// optional int32 index = 2;
inline bool ClientReq::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientReq::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientReq::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientReq::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 ClientReq::index() const {
  // @@protoc_insertion_point(field_get:demo_multi.ClientReq.index)
  return index_;
}
inline void ClientReq::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:demo_multi.ClientReq.index)
}

// -------------------------------------------------------------------

// ClientResp

// optional .demo_multi.BaseResp base = 1;
inline bool ClientResp::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientResp::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientResp::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientResp::clear_base() {
  if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
  clear_has_base();
}
inline const ::demo_multi::BaseResp& ClientResp::base() const {
  // @@protoc_insertion_point(field_get:demo_multi.ClientResp.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::demo_multi::BaseResp* ClientResp::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::demo_multi::BaseResp;
  // @@protoc_insertion_point(field_mutable:demo_multi.ClientResp.base)
  return base_;
}
inline ::demo_multi::BaseResp* ClientResp::release_base() {
  clear_has_base();
  ::demo_multi::BaseResp* temp = base_;
  base_ = NULL;
  return temp;
}
inline void ClientResp::set_allocated_base(::demo_multi::BaseResp* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ClientResp.base)
}

// optional string message = 2;
inline bool ClientResp::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientResp::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientResp::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientResp::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& ClientResp::message() const {
  // @@protoc_insertion_point(field_get:demo_multi.ClientResp.message)
  return *message_;
}
inline void ClientResp::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:demo_multi.ClientResp.message)
}
inline void ClientResp::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:demo_multi.ClientResp.message)
}
inline void ClientResp::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:demo_multi.ClientResp.message)
}
inline ::std::string* ClientResp::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:demo_multi.ClientResp.message)
  return message_;
}
inline ::std::string* ClientResp::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ClientResp::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:demo_multi.ClientResp.message)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace demo_multi

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_demo_5fmulti_2eproto__INCLUDED
