// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_multi.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "demo_multi.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace demo_multi {

namespace {

const ::google::protobuf::Descriptor* BaseResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BaseResp_reflection_ = NULL;
const ::google::protobuf::Descriptor* AclReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AclReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* AclResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AclResp_reflection_ = NULL;
const ::google::protobuf::Descriptor* StudyReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StudyReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* StudyResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StudyResp_reflection_ = NULL;
const ::google::protobuf::Descriptor* ControlReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ControlReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* ControlResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ControlResp_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientResp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_demo_5fmulti_2eproto() {
  protobuf_AddDesc_demo_5fmulti_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "demo_multi.proto");
  GOOGLE_CHECK(file != NULL);
  BaseResp_descriptor_ = file->message_type(0);
  static const int BaseResp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseResp, ret_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseResp, ret_msg_),
  };
  BaseResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BaseResp_descriptor_,
      BaseResp::default_instance_,
      BaseResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BaseResp));
  AclReq_descriptor_ = file->message_type(1);
  static const int AclReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclReq, user_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclReq, resource_),
  };
  AclReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AclReq_descriptor_,
      AclReq::default_instance_,
      AclReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AclReq));
  AclResp_descriptor_ = file->message_type(2);
  static const int AclResp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclResp, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclResp, is_allow_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclResp, detail_),
  };
  AclResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AclResp_descriptor_,
      AclResp::default_instance_,
      AclResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AclResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AclResp));
  StudyReq_descriptor_ = file->message_type(3);
  static const int StudyReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyReq, student_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyReq, subject_),
  };
  StudyReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StudyReq_descriptor_,
      StudyReq::default_instance_,
      StudyReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StudyReq));
  StudyResp_descriptor_ = file->message_type(4);
  static const int StudyResp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyResp, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyResp, num_subject_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyResp, detail_),
  };
  StudyResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StudyResp_descriptor_,
      StudyResp::default_instance_,
      StudyResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StudyResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StudyResp));
  ControlReq_descriptor_ = file->message_type(5);
  static const int ControlReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlReq, command_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlReq, target_),
  };
  ControlReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ControlReq_descriptor_,
      ControlReq::default_instance_,
      ControlReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ControlReq));
  ControlResp_descriptor_ = file->message_type(6);
  static const int ControlResp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlResp, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlResp, acl_result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlResp, study_result_),
  };
  ControlResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ControlResp_descriptor_,
      ControlResp::default_instance_,
      ControlResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ControlResp));
  ClientReq_descriptor_ = file->message_type(7);
  static const int ClientReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientReq, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientReq, index_),
  };
  ClientReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientReq_descriptor_,
      ClientReq::default_instance_,
      ClientReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientReq));
  ClientResp_descriptor_ = file->message_type(8);
  static const int ClientResp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientResp, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientResp, message_),
  };
  ClientResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientResp_descriptor_,
      ClientResp::default_instance_,
      ClientResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientResp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_demo_5fmulti_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BaseResp_descriptor_, &BaseResp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AclReq_descriptor_, &AclReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AclResp_descriptor_, &AclResp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StudyReq_descriptor_, &StudyReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StudyResp_descriptor_, &StudyResp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ControlReq_descriptor_, &ControlReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ControlResp_descriptor_, &ControlResp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientReq_descriptor_, &ClientReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientResp_descriptor_, &ClientResp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_demo_5fmulti_2eproto() {
  delete BaseResp::default_instance_;
  delete BaseResp_reflection_;
  delete AclReq::default_instance_;
  delete AclReq_reflection_;
  delete AclResp::default_instance_;
  delete AclResp_reflection_;
  delete StudyReq::default_instance_;
  delete StudyReq_reflection_;
  delete StudyResp::default_instance_;
  delete StudyResp_reflection_;
  delete ControlReq::default_instance_;
  delete ControlReq_reflection_;
  delete ControlResp::default_instance_;
  delete ControlResp_reflection_;
  delete ClientReq::default_instance_;
  delete ClientReq_reflection_;
  delete ClientResp::default_instance_;
  delete ClientResp_reflection_;
}

void protobuf_AddDesc_demo_5fmulti_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020demo_multi.proto\022\ndemo_multi\"-\n\010BaseRe"
    "sp\022\020\n\010ret_code\030\001 \001(\005\022\017\n\007ret_msg\030\002 \001(\t\"-\n"
    "\006AclReq\022\021\n\tuser_name\030\001 \001(\t\022\020\n\010resource\030\002"
    " \001(\t\"O\n\007AclResp\022\"\n\004base\030\001 \001(\0132\024.demo_mul"
    "ti.BaseResp\022\020\n\010is_allow\030\002 \001(\010\022\016\n\006detail\030"
    "\003 \001(\t\"1\n\010StudyReq\022\024\n\014student_name\030\001 \001(\t\022"
    "\017\n\007subject\030\002 \001(\t\"T\n\tStudyResp\022\"\n\004base\030\001 "
    "\001(\0132\024.demo_multi.BaseResp\022\023\n\013num_subject"
    "\030\002 \001(\005\022\016\n\006detail\030\003 \001(\t\"-\n\nControlReq\022\017\n\007"
    "command\030\001 \001(\t\022\016\n\006target\030\002 \001(\t\"[\n\013Control"
    "Resp\022\"\n\004base\030\001 \001(\0132\024.demo_multi.BaseResp"
    "\022\022\n\nacl_result\030\002 \001(\t\022\024\n\014study_result\030\003 \001"
    "(\t\"+\n\tClientReq\022\017\n\007message\030\001 \001(\t\022\r\n\005inde"
    "x\030\002 \001(\005\"A\n\nClientResp\022\"\n\004base\030\001 \001(\0132\024.de"
    "mo_multi.BaseResp\022\017\n\007message\030\002 \001(\t", 594);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "demo_multi.proto", &protobuf_RegisterTypes);
  BaseResp::default_instance_ = new BaseResp();
  AclReq::default_instance_ = new AclReq();
  AclResp::default_instance_ = new AclResp();
  StudyReq::default_instance_ = new StudyReq();
  StudyResp::default_instance_ = new StudyResp();
  ControlReq::default_instance_ = new ControlReq();
  ControlResp::default_instance_ = new ControlResp();
  ClientReq::default_instance_ = new ClientReq();
  ClientResp::default_instance_ = new ClientResp();
  BaseResp::default_instance_->InitAsDefaultInstance();
  AclReq::default_instance_->InitAsDefaultInstance();
  AclResp::default_instance_->InitAsDefaultInstance();
  StudyReq::default_instance_->InitAsDefaultInstance();
  StudyResp::default_instance_->InitAsDefaultInstance();
  ControlReq::default_instance_->InitAsDefaultInstance();
  ControlResp::default_instance_->InitAsDefaultInstance();
  ClientReq::default_instance_->InitAsDefaultInstance();
  ClientResp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_demo_5fmulti_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_demo_5fmulti_2eproto {
  StaticDescriptorInitializer_demo_5fmulti_2eproto() {
    protobuf_AddDesc_demo_5fmulti_2eproto();
  }
} static_descriptor_initializer_demo_5fmulti_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int BaseResp::kRetCodeFieldNumber;
const int BaseResp::kRetMsgFieldNumber;
#endif  // !_MSC_VER

BaseResp::BaseResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.BaseResp)
}

void BaseResp::InitAsDefaultInstance() {
}

BaseResp::BaseResp(const BaseResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.BaseResp)
}

void BaseResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ret_code_ = 0;
  ret_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BaseResp::~BaseResp() {
  // @@protoc_insertion_point(destructor:demo_multi.BaseResp)
  SharedDtor();
}

void BaseResp::SharedDtor() {
  if (ret_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ret_msg_;
  }
  if (this != default_instance_) {
  }
}

void BaseResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BaseResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BaseResp_descriptor_;
}

const BaseResp& BaseResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

BaseResp* BaseResp::default_instance_ = NULL;

BaseResp* BaseResp::New() const {
  return new BaseResp;
}

void BaseResp::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    ret_code_ = 0;
    if (has_ret_msg()) {
      if (ret_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        ret_msg_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BaseResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.BaseResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 ret_code = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_code_)));
          set_has_ret_code();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_ret_msg;
        break;
      }

      // optional string ret_msg = 2;
      case 2: {
        if (tag == 18) {
         parse_ret_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ret_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ret_msg().data(), this->ret_msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ret_msg");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.BaseResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.BaseResp)
  return false;
#undef DO_
}

void BaseResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.BaseResp)
  // optional int32 ret_code = 1;
  if (has_ret_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ret_code(), output);
  }

  // optional string ret_msg = 2;
  if (has_ret_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ret_msg().data(), this->ret_msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ret_msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->ret_msg(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.BaseResp)
}

::google::protobuf::uint8* BaseResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.BaseResp)
  // optional int32 ret_code = 1;
  if (has_ret_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ret_code(), target);
  }

  // optional string ret_msg = 2;
  if (has_ret_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ret_msg().data(), this->ret_msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ret_msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->ret_msg(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.BaseResp)
  return target;
}

int BaseResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 ret_code = 1;
    if (has_ret_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ret_code());
    }

    // optional string ret_msg = 2;
    if (has_ret_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ret_msg());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BaseResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BaseResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BaseResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BaseResp::MergeFrom(const BaseResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ret_code()) {
      set_ret_code(from.ret_code());
    }
    if (from.has_ret_msg()) {
      set_ret_msg(from.ret_msg());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BaseResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BaseResp::CopyFrom(const BaseResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseResp::IsInitialized() const {

  return true;
}

void BaseResp::Swap(BaseResp* other) {
  if (other != this) {
    std::swap(ret_code_, other->ret_code_);
    std::swap(ret_msg_, other->ret_msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BaseResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BaseResp_descriptor_;
  metadata.reflection = BaseResp_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AclReq::kUserNameFieldNumber;
const int AclReq::kResourceFieldNumber;
#endif  // !_MSC_VER

AclReq::AclReq()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.AclReq)
}

void AclReq::InitAsDefaultInstance() {
}

AclReq::AclReq(const AclReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.AclReq)
}

void AclReq::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  resource_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AclReq::~AclReq() {
  // @@protoc_insertion_point(destructor:demo_multi.AclReq)
  SharedDtor();
}

void AclReq::SharedDtor() {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete user_name_;
  }
  if (resource_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete resource_;
  }
  if (this != default_instance_) {
  }
}

void AclReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AclReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AclReq_descriptor_;
}

const AclReq& AclReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

AclReq* AclReq::default_instance_ = NULL;

AclReq* AclReq::New() const {
  return new AclReq;
}

void AclReq::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_user_name()) {
      if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        user_name_->clear();
      }
    }
    if (has_resource()) {
      if (resource_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        resource_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AclReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.AclReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string user_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->user_name().data(), this->user_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "user_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_resource;
        break;
      }

      // optional string resource = 2;
      case 2: {
        if (tag == 18) {
         parse_resource:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_resource()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->resource().data(), this->resource().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "resource");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.AclReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.AclReq)
  return false;
#undef DO_
}

void AclReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.AclReq)
  // optional string user_name = 1;
  if (has_user_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_name().data(), this->user_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "user_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->user_name(), output);
  }

  // optional string resource = 2;
  if (has_resource()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->resource().data(), this->resource().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "resource");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->resource(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.AclReq)
}

::google::protobuf::uint8* AclReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.AclReq)
  // optional string user_name = 1;
  if (has_user_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_name().data(), this->user_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "user_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->user_name(), target);
  }

  // optional string resource = 2;
  if (has_resource()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->resource().data(), this->resource().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "resource");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->resource(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.AclReq)
  return target;
}

int AclReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string user_name = 1;
    if (has_user_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->user_name());
    }

    // optional string resource = 2;
    if (has_resource()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->resource());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AclReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AclReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AclReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AclReq::MergeFrom(const AclReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_name()) {
      set_user_name(from.user_name());
    }
    if (from.has_resource()) {
      set_resource(from.resource());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AclReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AclReq::CopyFrom(const AclReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AclReq::IsInitialized() const {

  return true;
}

void AclReq::Swap(AclReq* other) {
  if (other != this) {
    std::swap(user_name_, other->user_name_);
    std::swap(resource_, other->resource_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AclReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AclReq_descriptor_;
  metadata.reflection = AclReq_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AclResp::kBaseFieldNumber;
const int AclResp::kIsAllowFieldNumber;
const int AclResp::kDetailFieldNumber;
#endif  // !_MSC_VER

AclResp::AclResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.AclResp)
}

void AclResp::InitAsDefaultInstance() {
  base_ = const_cast< ::demo_multi::BaseResp*>(&::demo_multi::BaseResp::default_instance());
}

AclResp::AclResp(const AclResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.AclResp)
}

void AclResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  base_ = NULL;
  is_allow_ = false;
  detail_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AclResp::~AclResp() {
  // @@protoc_insertion_point(destructor:demo_multi.AclResp)
  SharedDtor();
}

void AclResp::SharedDtor() {
  if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete detail_;
  }
  if (this != default_instance_) {
    delete base_;
  }
}

void AclResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AclResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AclResp_descriptor_;
}

const AclResp& AclResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

AclResp* AclResp::default_instance_ = NULL;

AclResp* AclResp::New() const {
  return new AclResp;
}

void AclResp::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_base()) {
      if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
    }
    is_allow_ = false;
    if (has_detail()) {
      if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        detail_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AclResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.AclResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .demo_multi.BaseResp base = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_is_allow;
        break;
      }

      // optional bool is_allow = 2;
      case 2: {
        if (tag == 16) {
         parse_is_allow:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_allow_)));
          set_has_is_allow();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_detail;
        break;
      }

      // optional string detail = 3;
      case 3: {
        if (tag == 26) {
         parse_detail:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_detail()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->detail().data(), this->detail().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "detail");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.AclResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.AclResp)
  return false;
#undef DO_
}

void AclResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.AclResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }

  // optional bool is_allow = 2;
  if (has_is_allow()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->is_allow(), output);
  }

  // optional string detail = 3;
  if (has_detail()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->detail().data(), this->detail().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "detail");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->detail(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.AclResp)
}

::google::protobuf::uint8* AclResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.AclResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }

  // optional bool is_allow = 2;
  if (has_is_allow()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->is_allow(), target);
  }

  // optional string detail = 3;
  if (has_detail()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->detail().data(), this->detail().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "detail");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->detail(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.AclResp)
  return target;
}

int AclResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .demo_multi.BaseResp base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }

    // optional bool is_allow = 2;
    if (has_is_allow()) {
      total_size += 1 + 1;
    }

    // optional string detail = 3;
    if (has_detail()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->detail());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AclResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AclResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AclResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AclResp::MergeFrom(const AclResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::demo_multi::BaseResp::MergeFrom(from.base());
    }
    if (from.has_is_allow()) {
      set_is_allow(from.is_allow());
    }
    if (from.has_detail()) {
      set_detail(from.detail());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AclResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AclResp::CopyFrom(const AclResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AclResp::IsInitialized() const {

  return true;
}

void AclResp::Swap(AclResp* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(is_allow_, other->is_allow_);
    std::swap(detail_, other->detail_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AclResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AclResp_descriptor_;
  metadata.reflection = AclResp_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StudyReq::kStudentNameFieldNumber;
const int StudyReq::kSubjectFieldNumber;
#endif  // !_MSC_VER

StudyReq::StudyReq()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.StudyReq)
}

void StudyReq::InitAsDefaultInstance() {
}

StudyReq::StudyReq(const StudyReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.StudyReq)
}

void StudyReq::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  student_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StudyReq::~StudyReq() {
  // @@protoc_insertion_point(destructor:demo_multi.StudyReq)
  SharedDtor();
}

void StudyReq::SharedDtor() {
  if (student_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete student_name_;
  }
  if (subject_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete subject_;
  }
  if (this != default_instance_) {
  }
}

void StudyReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StudyReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StudyReq_descriptor_;
}

const StudyReq& StudyReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

StudyReq* StudyReq::default_instance_ = NULL;

StudyReq* StudyReq::New() const {
  return new StudyReq;
}

void StudyReq::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_student_name()) {
      if (student_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        student_name_->clear();
      }
    }
    if (has_subject()) {
      if (subject_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        subject_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StudyReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.StudyReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string student_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_student_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->student_name().data(), this->student_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "student_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_subject;
        break;
      }

      // optional string subject = 2;
      case 2: {
        if (tag == 18) {
         parse_subject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_subject()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->subject().data(), this->subject().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "subject");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.StudyReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.StudyReq)
  return false;
#undef DO_
}

void StudyReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.StudyReq)
  // optional string student_name = 1;
  if (has_student_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->student_name().data(), this->student_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "student_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->student_name(), output);
  }

  // optional string subject = 2;
  if (has_subject()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->subject().data(), this->subject().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "subject");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->subject(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.StudyReq)
}

::google::protobuf::uint8* StudyReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.StudyReq)
  // optional string student_name = 1;
  if (has_student_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->student_name().data(), this->student_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "student_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->student_name(), target);
  }

  // optional string subject = 2;
  if (has_subject()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->subject().data(), this->subject().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "subject");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->subject(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.StudyReq)
  return target;
}

int StudyReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string student_name = 1;
    if (has_student_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->student_name());
    }

    // optional string subject = 2;
    if (has_subject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->subject());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StudyReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StudyReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StudyReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StudyReq::MergeFrom(const StudyReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_student_name()) {
      set_student_name(from.student_name());
    }
    if (from.has_subject()) {
      set_subject(from.subject());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StudyReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StudyReq::CopyFrom(const StudyReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StudyReq::IsInitialized() const {

  return true;
}

void StudyReq::Swap(StudyReq* other) {
  if (other != this) {
    std::swap(student_name_, other->student_name_);
    std::swap(subject_, other->subject_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StudyReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StudyReq_descriptor_;
  metadata.reflection = StudyReq_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StudyResp::kBaseFieldNumber;
const int StudyResp::kNumSubjectFieldNumber;
const int StudyResp::kDetailFieldNumber;
#endif  // !_MSC_VER

StudyResp::StudyResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.StudyResp)
}

void StudyResp::InitAsDefaultInstance() {
  base_ = const_cast< ::demo_multi::BaseResp*>(&::demo_multi::BaseResp::default_instance());
}

StudyResp::StudyResp(const StudyResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.StudyResp)
}

void StudyResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  base_ = NULL;
  num_subject_ = 0;
  detail_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StudyResp::~StudyResp() {
  // @@protoc_insertion_point(destructor:demo_multi.StudyResp)
  SharedDtor();
}

void StudyResp::SharedDtor() {
  if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete detail_;
  }
  if (this != default_instance_) {
    delete base_;
  }
}

void StudyResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StudyResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StudyResp_descriptor_;
}

const StudyResp& StudyResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

StudyResp* StudyResp::default_instance_ = NULL;

StudyResp* StudyResp::New() const {
  return new StudyResp;
}

void StudyResp::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_base()) {
      if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
    }
    num_subject_ = 0;
    if (has_detail()) {
      if (detail_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        detail_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StudyResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.StudyResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .demo_multi.BaseResp base = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_num_subject;
        break;
      }

      // optional int32 num_subject = 2;
      case 2: {
        if (tag == 16) {
         parse_num_subject:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_subject_)));
          set_has_num_subject();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_detail;
        break;
      }

      // optional string detail = 3;
      case 3: {
        if (tag == 26) {
         parse_detail:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_detail()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->detail().data(), this->detail().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "detail");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.StudyResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.StudyResp)
  return false;
#undef DO_
}

void StudyResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.StudyResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }

  // optional int32 num_subject = 2;
  if (has_num_subject()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num_subject(), output);
  }

  // optional string detail = 3;
  if (has_detail()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->detail().data(), this->detail().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "detail");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->detail(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.StudyResp)
}

::google::protobuf::uint8* StudyResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.StudyResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }

  // optional int32 num_subject = 2;
  if (has_num_subject()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num_subject(), target);
  }

  // optional string detail = 3;
  if (has_detail()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->detail().data(), this->detail().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "detail");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->detail(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.StudyResp)
  return target;
}

int StudyResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .demo_multi.BaseResp base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }

    // optional int32 num_subject = 2;
    if (has_num_subject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_subject());
    }

    // optional string detail = 3;
    if (has_detail()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->detail());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StudyResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StudyResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StudyResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StudyResp::MergeFrom(const StudyResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::demo_multi::BaseResp::MergeFrom(from.base());
    }
    if (from.has_num_subject()) {
      set_num_subject(from.num_subject());
    }
    if (from.has_detail()) {
      set_detail(from.detail());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StudyResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StudyResp::CopyFrom(const StudyResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StudyResp::IsInitialized() const {

  return true;
}

void StudyResp::Swap(StudyResp* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(num_subject_, other->num_subject_);
    std::swap(detail_, other->detail_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StudyResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StudyResp_descriptor_;
  metadata.reflection = StudyResp_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ControlReq::kCommandFieldNumber;
const int ControlReq::kTargetFieldNumber;
#endif  // !_MSC_VER

ControlReq::ControlReq()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.ControlReq)
}

void ControlReq::InitAsDefaultInstance() {
}

ControlReq::ControlReq(const ControlReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.ControlReq)
}

void ControlReq::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  command_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ControlReq::~ControlReq() {
  // @@protoc_insertion_point(destructor:demo_multi.ControlReq)
  SharedDtor();
}

void ControlReq::SharedDtor() {
  if (command_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete command_;
  }
  if (target_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_;
  }
  if (this != default_instance_) {
  }
}

void ControlReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ControlReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ControlReq_descriptor_;
}

const ControlReq& ControlReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

ControlReq* ControlReq::default_instance_ = NULL;

ControlReq* ControlReq::New() const {
  return new ControlReq;
}

void ControlReq::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_command()) {
      if (command_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        command_->clear();
      }
    }
    if (has_target()) {
      if (target_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        target_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ControlReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.ControlReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string command = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->command().data(), this->command().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "command");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_target;
        break;
      }

      // optional string target = 2;
      case 2: {
        if (tag == 18) {
         parse_target:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_target()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->target().data(), this->target().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "target");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.ControlReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.ControlReq)
  return false;
#undef DO_
}

void ControlReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.ControlReq)
  // optional string command = 1;
  if (has_command()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->command().data(), this->command().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "command");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->command(), output);
  }

  // optional string target = 2;
  if (has_target()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->target().data(), this->target().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "target");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->target(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.ControlReq)
}

::google::protobuf::uint8* ControlReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.ControlReq)
  // optional string command = 1;
  if (has_command()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->command().data(), this->command().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "command");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->command(), target);
  }

  // optional string target = 2;
  if (has_target()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->target().data(), this->target().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "target");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->target(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.ControlReq)
  return target;
}

int ControlReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string command = 1;
    if (has_command()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->command());
    }

    // optional string target = 2;
    if (has_target()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->target());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ControlReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ControlReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ControlReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ControlReq::MergeFrom(const ControlReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_command()) {
      set_command(from.command());
    }
    if (from.has_target()) {
      set_target(from.target());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ControlReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlReq::CopyFrom(const ControlReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlReq::IsInitialized() const {

  return true;
}

void ControlReq::Swap(ControlReq* other) {
  if (other != this) {
    std::swap(command_, other->command_);
    std::swap(target_, other->target_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ControlReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ControlReq_descriptor_;
  metadata.reflection = ControlReq_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ControlResp::kBaseFieldNumber;
const int ControlResp::kAclResultFieldNumber;
const int ControlResp::kStudyResultFieldNumber;
#endif  // !_MSC_VER

ControlResp::ControlResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.ControlResp)
}

void ControlResp::InitAsDefaultInstance() {
  base_ = const_cast< ::demo_multi::BaseResp*>(&::demo_multi::BaseResp::default_instance());
}

ControlResp::ControlResp(const ControlResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.ControlResp)
}

void ControlResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  base_ = NULL;
  acl_result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  study_result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ControlResp::~ControlResp() {
  // @@protoc_insertion_point(destructor:demo_multi.ControlResp)
  SharedDtor();
}

void ControlResp::SharedDtor() {
  if (acl_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete acl_result_;
  }
  if (study_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete study_result_;
  }
  if (this != default_instance_) {
    delete base_;
  }
}

void ControlResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ControlResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ControlResp_descriptor_;
}

const ControlResp& ControlResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

ControlResp* ControlResp::default_instance_ = NULL;

ControlResp* ControlResp::New() const {
  return new ControlResp;
}

void ControlResp::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_base()) {
      if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
    }
    if (has_acl_result()) {
      if (acl_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        acl_result_->clear();
      }
    }
    if (has_study_result()) {
      if (study_result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        study_result_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ControlResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.ControlResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .demo_multi.BaseResp base = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_acl_result;
        break;
      }

      // optional string acl_result = 2;
      case 2: {
        if (tag == 18) {
         parse_acl_result:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_acl_result()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->acl_result().data(), this->acl_result().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "acl_result");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_study_result;
        break;
      }

      // optional string study_result = 3;
      case 3: {
        if (tag == 26) {
         parse_study_result:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_study_result()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->study_result().data(), this->study_result().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "study_result");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.ControlResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.ControlResp)
  return false;
#undef DO_
}

void ControlResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.ControlResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }

  // optional string acl_result = 2;
  if (has_acl_result()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->acl_result().data(), this->acl_result().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "acl_result");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->acl_result(), output);
  }

  // optional string study_result = 3;
  if (has_study_result()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->study_result().data(), this->study_result().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "study_result");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->study_result(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.ControlResp)
}

::google::protobuf::uint8* ControlResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.ControlResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }

  // optional string acl_result = 2;
  if (has_acl_result()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->acl_result().data(), this->acl_result().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "acl_result");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->acl_result(), target);
  }

  // optional string study_result = 3;
  if (has_study_result()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->study_result().data(), this->study_result().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "study_result");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->study_result(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.ControlResp)
  return target;
}

int ControlResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .demo_multi.BaseResp base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }

    // optional string acl_result = 2;
    if (has_acl_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->acl_result());
    }

    // optional string study_result = 3;
    if (has_study_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->study_result());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ControlResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ControlResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ControlResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ControlResp::MergeFrom(const ControlResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::demo_multi::BaseResp::MergeFrom(from.base());
    }
    if (from.has_acl_result()) {
      set_acl_result(from.acl_result());
    }
    if (from.has_study_result()) {
      set_study_result(from.study_result());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ControlResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlResp::CopyFrom(const ControlResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlResp::IsInitialized() const {

  return true;
}

void ControlResp::Swap(ControlResp* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(acl_result_, other->acl_result_);
    std::swap(study_result_, other->study_result_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ControlResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ControlResp_descriptor_;
  metadata.reflection = ControlResp_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClientReq::kMessageFieldNumber;
const int ClientReq::kIndexFieldNumber;
#endif  // !_MSC_VER

ClientReq::ClientReq()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.ClientReq)
}

void ClientReq::InitAsDefaultInstance() {
}

ClientReq::ClientReq(const ClientReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.ClientReq)
}

void ClientReq::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  index_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientReq::~ClientReq() {
  // @@protoc_insertion_point(destructor:demo_multi.ClientReq)
  SharedDtor();
}

void ClientReq::SharedDtor() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (this != default_instance_) {
  }
}

void ClientReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientReq_descriptor_;
}

const ClientReq& ClientReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

ClientReq* ClientReq::default_instance_ = NULL;

ClientReq* ClientReq::New() const {
  return new ClientReq;
}

void ClientReq::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_message()) {
      if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        message_->clear();
      }
    }
    index_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClientReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.ClientReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string message = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "message");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_index;
        break;
      }

      // optional int32 index = 2;
      case 2: {
        if (tag == 16) {
         parse_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &index_)));
          set_has_index();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.ClientReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.ClientReq)
  return false;
#undef DO_
}

void ClientReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.ClientReq)
  // optional string message = 1;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  // optional int32 index = 2;
  if (has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->index(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.ClientReq)
}

::google::protobuf::uint8* ClientReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.ClientReq)
  // optional string message = 1;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  // optional int32 index = 2;
  if (has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->index(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.ClientReq)
  return target;
}

int ClientReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string message = 1;
    if (has_message()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->message());
    }

    // optional int32 index = 2;
    if (has_index()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->index());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClientReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClientReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClientReq::MergeFrom(const ClientReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_message()) {
      set_message(from.message());
    }
    if (from.has_index()) {
      set_index(from.index());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClientReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientReq::CopyFrom(const ClientReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientReq::IsInitialized() const {

  return true;
}

void ClientReq::Swap(ClientReq* other) {
  if (other != this) {
    std::swap(message_, other->message_);
    std::swap(index_, other->index_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClientReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientReq_descriptor_;
  metadata.reflection = ClientReq_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClientResp::kBaseFieldNumber;
const int ClientResp::kMessageFieldNumber;
#endif  // !_MSC_VER

ClientResp::ClientResp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo_multi.ClientResp)
}

void ClientResp::InitAsDefaultInstance() {
  base_ = const_cast< ::demo_multi::BaseResp*>(&::demo_multi::BaseResp::default_instance());
}

ClientResp::ClientResp(const ClientResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo_multi.ClientResp)
}

void ClientResp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  base_ = NULL;
  message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientResp::~ClientResp() {
  // @@protoc_insertion_point(destructor:demo_multi.ClientResp)
  SharedDtor();
}

void ClientResp::SharedDtor() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (this != default_instance_) {
    delete base_;
  }
}

void ClientResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientResp_descriptor_;
}

const ClientResp& ClientResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_demo_5fmulti_2eproto();
  return *default_instance_;
}

ClientResp* ClientResp::default_instance_ = NULL;

ClientResp* ClientResp::New() const {
  return new ClientResp;
}

void ClientResp::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_base()) {
      if (base_ != NULL) base_->::demo_multi::BaseResp::Clear();
    }
    if (has_message()) {
      if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        message_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClientResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo_multi.ClientResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .demo_multi.BaseResp base = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_message;
        break;
      }

      // optional string message = 2;
      case 2: {
        if (tag == 18) {
         parse_message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "message");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo_multi.ClientResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo_multi.ClientResp)
  return false;
#undef DO_
}

void ClientResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo_multi.ClientResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }

  // optional string message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo_multi.ClientResp)
}

::google::protobuf::uint8* ClientResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo_multi.ClientResp)
  // optional .demo_multi.BaseResp base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }

  // optional string message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo_multi.ClientResp)
  return target;
}

int ClientResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .demo_multi.BaseResp base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }

    // optional string message = 2;
    if (has_message()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->message());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClientResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClientResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClientResp::MergeFrom(const ClientResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::demo_multi::BaseResp::MergeFrom(from.base());
    }
    if (from.has_message()) {
      set_message(from.message());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClientResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientResp::CopyFrom(const ClientResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientResp::IsInitialized() const {

  return true;
}

void ClientResp::Swap(ClientResp* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(message_, other->message_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClientResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientResp_descriptor_;
  metadata.reflection = ClientResp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace demo_multi

// @@protoc_insertion_point(global_scope)
